// ─────────────────────────────────────────────────────────────
// MACHINE MIND v4.0 — Rule Table (300+ rules)
// Every rule is fully written out. No placeholders. No stubs.
// All response fields are template keys matching templates.ts.
// Sorted by priority (highest first), organized by category.
// ─────────────────────────────────────────────────────────────

import type { Rule } from '../types'

export const RULES: Rule[] = [

  // ═══════════════════════════════════════════════════════════
  // EDGE CASES — priority 100
  // ═══════════════════════════════════════════════════════════
  {
    id: 'EDGE_001',
    priority: 100,
    patterns: [/^\s*$/],
    contextRequired: null,
    response: 'UNKNOWN',
    setsContext: null,
    tool: null,
  },
  {
    id: 'EDGE_002',
    priority: 100,
    patterns: [/^[\s\S]{500,}$/],
    contextRequired: null,
    response: 'UNKNOWN',
    setsContext: null,
    tool: null,
  },
  {
    id: 'EDGE_003',
    priority: 100,
    patterns: [/^[^\w\s]+$/, /^[^a-zA-Z0-9]+$/],
    contextRequired: null,
    response: 'UNKNOWN',
    setsContext: null,
    tool: null,
  },
  {
    id: 'EDGE_004',
    priority: 100,
    patterns: [/^(.)\1{4,}$/, /^(\b\w+\b)\s+\1\s+\1\s+\1/],
    contextRequired: null,
    response: 'UNKNOWN',
    setsContext: null,
    tool: null,
  },
  {
    id: 'EDGE_005',
    priority: 100,
    patterns: [/^[bcdfghjklmnpqrstvwxyz]{5,}$/i],
    contextRequired: null,
    response: 'UNKNOWN',
    setsContext: null,
    tool: null,
  },
  {
    id: 'EDGE_006',
    priority: 100,
    patterns: [/^\d+$/],
    contextRequired: null,
    response: 'UNKNOWN',
    setsContext: null,
    tool: null,
  },
  {
    id: 'EDGE_007',
    priority: 100,
    patterns: [/^\w$/],
    contextRequired: null,
    response: 'UNKNOWN',
    setsContext: null,
    tool: null,
  },
  {
    id: 'EDGE_008',
    priority: 100,
    patterns: [/^\w{1,3}$/],
    contextRequired: null,
    response: 'UNKNOWN',
    setsContext: null,
    tool: null,
  },
  {
    id: 'EDGE_009',
    priority: 100,
    patterns: [/^[A-Z\s!]{5,}$/],
    contextRequired: null,
    response: 'UNKNOWN',
    setsContext: null,
    tool: null,
  },
  {
    id: 'EDGE_010',
    priority: 100,
    patterns: [/[\u4e00-\u9fff]+/, /[\u3040-\u309f]+/, /[\u0400-\u04ff]+/],
    contextRequired: null,
    response: 'UNKNOWN',
    setsContext: null,
    tool: null,
  },

  // ═══════════════════════════════════════════════════════════
  // MATH — priority 25
  // ═══════════════════════════════════════════════════════════
  {
    id: 'MATH_001',
    priority: 25,
    patterns: [/^!calc\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MATH',
    tool: 'calculator',
  },
  {
    id: 'MATH_002',
    priority: 25,
    patterns: [/\b(calculate|compute|evaluate|solve|work out|figure out)\b.*[\d(]/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MATH',
    tool: 'calculator',
  },
  {
    id: 'MATH_003',
    priority: 25,
    patterns: [/^\s*-?[\d(].*[\+\-\*\/\^%÷×].*-?[\d)]/],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MATH',
    tool: 'calculator',
  },
  {
    id: 'MATH_004',
    priority: 25,
    patterns: [/\bwhat('?s| is) [\d.]+\s*[\+\-\*\/\^%÷×]\s*[\d.]+\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MATH',
    tool: 'calculator',
  },
  {
    id: 'MATH_005',
    priority: 25,
    patterns: [/\b(square root|sqrt|∛|cube root) of [\d.]+\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MATH',
    tool: 'calculator',
  },
  {
    id: 'MATH_006',
    priority: 25,
    patterns: [/\b[\d.]+ (percent|%) of [\d.]+\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MATH',
    tool: 'calculator',
  },
  {
    id: 'MATH_007',
    priority: 25,
    patterns: [/\b(factorial|log|ln|sin|cos|tan|asin|acos|atan|abs|floor|ceil|round) of [\d.]+\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MATH',
    tool: 'calculator',
  },
  {
    id: 'MATH_008',
    priority: 25,
    patterns: [/\b[\d.]+ (plus|minus|times|divided by|over|mod|to the power of)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MATH',
    tool: 'calculator',
  },
  {
    id: 'MATH_009',
    priority: 25,
    patterns: [/\bhow much is\b.*[\d]/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MATH',
    tool: 'calculator',
  },
  {
    id: 'MATH_010',
    priority: 25,
    patterns: [/\b(double|triple|quadruple|half|third|quarter) of [\d.]+\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MATH',
    tool: 'calculator',
  },
  {
    id: 'MATH_011',
    priority: 25,
    patterns: [/\bwhat is [\d.]+\s*[\+\-\*\/\^%]\s*[\d.]+\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MATH',
    tool: 'calculator',
  },
  {
    id: 'MATH_012',
    priority: 25,
    patterns: [/\b(calculate|compute|what is|what'?s)\s+[\d.]+\s*(squared|cubed)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MATH',
    tool: 'calculator',
  },
  {
    id: 'MATH_013',
    priority: 25,
    patterns: [/\b[\d.]+\s*%\s*(of|off)\s*[\d.]+\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MATH',
    tool: 'calculator',
  },
  {
    id: 'MATH_014',
    priority: 25,
    patterns: [/\broot of\s+[\d.]+\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MATH',
    tool: 'calculator',
  },
  {
    id: 'MATH_015',
    priority: 25,
    patterns: [/\b(power|exponent|raise)\s+[\d.]+\s*(to|by)\s*[\d.]*\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MATH',
    tool: 'calculator',
  },
  {
    id: 'MATH_016',
    priority: 25,
    patterns: [/\b[\d.]+\s*(!|factorial)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MATH',
    tool: 'calculator',
  },
  {
    id: 'MATH_017',
    priority: 25,
    patterns: [/\b(sin|cos|tan|log|ln|sqrt|abs)\s*\(/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MATH',
    tool: 'calculator',
  },
  {
    id: 'MATH_018',
    priority: 25,
    patterns: [/\bpi\b.*[\d+\-*/]/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MATH',
    tool: 'calculator',
  },
  {
    id: 'MATH_019',
    priority: 25,
    patterns: [/\baverage\s+(of|mean\s+of)?\s*[\d]/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MATH',
    tool: 'calculator',
  },
  {
    id: 'MATH_020',
    priority: 25,
    patterns: [/\b(round|floor|ceil|abs)\s*\(?\s*[\d.]+/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MATH',
    tool: 'calculator',
  },

  // ═══════════════════════════════════════════════════════════
  // GREETING — priority 25
  // ═══════════════════════════════════════════════════════════
  {
    id: 'GREET_001',
    priority: 25,
    patterns: [/^(hello|hi|hey|yo|sup|hiya|howdy|greetings|salutations)\b/i],
    contextRequired: null,
    response: 'GREET',
    setsContext: 'GREETED',
    tool: null,
  },
  {
    id: 'GREET_002',
    priority: 25,
    patterns: [/^good\s+(morning|afternoon|evening|day)\b/i],
    contextRequired: null,
    response: 'GREET_TIMED',
    setsContext: 'GREETED',
    tool: null,
  },
  {
    id: 'GREET_003',
    priority: 25,
    patterns: [/^(whaddup|wassup|wazzup|wup|s+up)\b/i],
    contextRequired: null,
    response: 'GREET_CASUAL',
    setsContext: 'GREETED',
    tool: null,
  },
  {
    id: 'GREET_004',
    priority: 25,
    patterns: [/^(ello|'ello|heya|oi|hoi)\b/i],
    contextRequired: null,
    response: 'GREET_CASUAL',
    setsContext: 'GREETED',
    tool: null,
  },
  {
    id: 'GREET_005',
    priority: 25,
    patterns: [/^(good\s+night|goodnight|g'?night|nite|gn)\b/i],
    contextRequired: null,
    response: 'FAREWELL_NIGHT',
    setsContext: null,
    tool: null,
  },
  {
    id: 'GREET_006',
    priority: 25,
    patterns: [/\bare you (there|awake|alive|online|working)\b/i],
    contextRequired: null,
    response: 'PRESENCE_CONFIRM',
    setsContext: null,
    tool: null,
  },
  {
    id: 'GREET_007',
    priority: 25,
    patterns: [/^(ping|test|hello\?|is this on|is this thing on)\b/i],
    contextRequired: null,
    response: 'PRESENCE_CONFIRM',
    setsContext: null,
    tool: null,
  },
  {
    id: 'GREET_008',
    priority: 25,
    patterns: [/\b(welcome back|long time|been a while)\b/i],
    contextRequired: null,
    response: 'GREET_RETURN',
    setsContext: 'GREETED',
    tool: null,
  },
  {
    id: 'GREET_009',
    priority: 25,
    patterns: [/^(hola|bonjour|namaste|ciao|aloha)\b/i],
    contextRequired: null,
    response: 'GREET',
    setsContext: 'GREETED',
    tool: null,
  },
  {
    id: 'GREET_010',
    priority: 25,
    patterns: [/^(what'?s up|wassup|how'?s it going|how goes it)\b/i],
    contextRequired: null,
    response: 'GREET_CASUAL',
    setsContext: 'GREETED',
    tool: null,
  },
  {
    id: 'GREET_011',
    priority: 25,
    patterns: [/^(ready|you there|you good|let'?s go|let'?s start)\b/i],
    contextRequired: null,
    response: 'PRESENCE_CONFIRM',
    setsContext: 'GREETED',
    tool: null,
  },
  {
    id: 'GREET_012',
    priority: 25,
    patterns: [/\b(nice to meet you|pleased to meet you)\b/i],
    contextRequired: null,
    response: 'GREET',
    setsContext: 'GREETED',
    tool: null,
  },

  // ═══════════════════════════════════════════════════════════
  // TIME — priority 24
  // ═══════════════════════════════════════════════════════════
  {
    id: 'TIME_001',
    priority: 24,
    patterns: [/^!clock\b/i, /^!time\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'TIME',
    tool: 'clock',
  },
  {
    id: 'TIME_002',
    priority: 24,
    patterns: [/\b(what (time|date|day) is it|current (time|date|day)|tell me the (time|date))\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'TIME',
    tool: 'clock',
  },
  {
    id: 'TIME_003',
    priority: 24,
    patterns: [/\btime in\b.{1,40}\b(right now|now|currently|rn|atm)?\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'TIME',
    tool: 'clock',
  },
  {
    id: 'TIME_004',
    priority: 24,
    patterns: [/\b\d{1,2}(:\d{2})?\s*(am|pm)?\s*(est|pst|gmt|utc|jst|ist|cet|aest)\s*to\s*(est|pst|gmt|utc|jst|ist|cet|aest)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'TIME',
    tool: 'clock',
  },
  {
    id: 'TIME_005',
    priority: 24,
    patterns: [/\b(days|hours|minutes|weeks)\s+(until|till|before|to|until)\b.{1,60}/i, /\bcountdown\s+to\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'TIME',
    tool: 'clock',
  },
  {
    id: 'TIME_006',
    priority: 24,
    patterns: [/\b(what time is it in|current time in|local time in)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'TIME',
    tool: 'clock',
  },
  {
    id: 'TIME_007',
    priority: 24,
    patterns: [/\b(in \d+ (hours?|minutes?|days?|weeks?)|from now|from today)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'TIME',
    tool: 'clock',
  },
  {
    id: 'TIME_008',
    priority: 24,
    patterns: [/\b(today|tomorrow|yesterday|this (week|month|year)|next (week|month|year))\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'TIME',
    tool: 'clock',
  },
  {
    id: 'TIME_009',
    priority: 24,
    patterns: [/\b(unix timestamp|epoch|posix)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'TIME',
    tool: 'clock',
  },
  {
    id: 'TIME_010',
    priority: 24,
    patterns: [/\b(leap year)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'TIME',
    tool: 'clock',
  },
  {
    id: 'TIME_011',
    priority: 24,
    patterns: [/\b(what day (is|was|will be)|day of (the )?week)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'TIME',
    tool: 'clock',
  },
  {
    id: 'TIME_012',
    priority: 24,
    patterns: [/\b(what date (is|was)|date of)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'TIME',
    tool: 'clock',
  },
  {
    id: 'TIME_013',
    priority: 24,
    patterns: [/\b(timezone|time zone)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'TIME',
    tool: 'clock',
  },
  {
    id: 'TIME_014',
    priority: 24,
    patterns: [/\b\d{1,2}(:\d{2})?\s*(am|pm)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'TIME',
    tool: 'clock',
  },
  {
    id: 'TIME_015',
    priority: 24,
    patterns: [/\b(what time does|when does|when is)\b.{1,40}\b(start|end|begin|close|open)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'TIME',
    tool: 'clock',
  },
  {
    id: 'TIME_016',
    priority: 24,
    patterns: [/\b(how many (days|hours|minutes|seconds) (until|till|between|from))\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'TIME',
    tool: 'clock',
  },
  {
    id: 'TIME_017',
    priority: 24,
    patterns: [/\b(what time is it|time now|current time)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'TIME',
    tool: 'clock',
  },
  {
    id: 'TIME_018',
    priority: 24,
    patterns: [/\b(relative time|time difference|time offset)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'TIME',
    tool: 'clock',
  },

  // ═══════════════════════════════════════════════════════════
  // FAREWELL — priority 24
  // ═══════════════════════════════════════════════════════════
  {
    id: 'FARE_001',
    priority: 24,
    patterns: [/\b(bye|goodbye|see\s+(you|ya|u)|later|take\s+care|farewell|ciao|adios|auf\s+wiedersehen|arrivederci|sayonara)\b/i],
    contextRequired: null,
    response: 'FAREWELL',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FARE_002',
    priority: 24,
    patterns: [/\b(gotta go|gotta bounce|i'm (out|done|off|leaving|heading out)|signing off|peace out|deuces|laters|ttyl|ttfn|gtg)\b/i],
    contextRequired: null,
    response: 'FAREWELL_CASUAL',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FARE_003',
    priority: 24,
    patterns: [/\b(talk (to you )?(later|soon)|catch (you|ya) (later|soon)|be back (later|soon))\b/i],
    contextRequired: null,
    response: 'FAREWELL_BRBL',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FARE_004',
    priority: 24,
    patterns: [/^(good\s+night|goodnight|gn|nite|g'?night)\b/i],
    contextRequired: null,
    response: 'FAREWELL_NIGHT',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FARE_005',
    priority: 24,
    patterns: [/\bi('m| am) (done|finished|out of here|logging off)\b/i],
    contextRequired: null,
    response: 'FAREWELL_CASUAL',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FARE_006',
    priority: 24,
    patterns: [/\b(catch you on the flip side|until next time|until we meet again)\b/i],
    contextRequired: null,
    response: 'FAREWELL',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FARE_007',
    priority: 24,
    patterns: [/\b(see ya|see u|cu|cya)\b/i],
    contextRequired: null,
    response: 'FAREWELL_CASUAL',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FARE_008',
    priority: 24,
    patterns: [/\bi('ll| will) (be going|head out|take off) now\b/i],
    contextRequired: null,
    response: 'FAREWELL',
    setsContext: null,
    tool: null,
  },

  // ═══════════════════════════════════════════════════════════
  // GRATITUDE — priority 23
  // ═══════════════════════════════════════════════════════════
  {
    id: 'GRAT_001',
    priority: 23,
    patterns: [/\b(thanks|thank you|thank u|thx|ty|cheers|appreciate (it|that|this|you)|much appreciated|grateful)\b/i],
    contextRequired: null,
    response: 'GRATITUDE',
    setsContext: null,
    tool: null,
  },
  {
    id: 'GRAT_002',
    priority: 23,
    patterns: [/\byou'?re (a )?(great|amazing|awesome|brilliant|the best|incredible|fantastic|genius)\b/i],
    contextRequired: null,
    response: 'GRATITUDE_COMPLIMENT',
    setsContext: null,
    tool: null,
  },
  {
    id: 'GRAT_003',
    priority: 23,
    patterns: [/\bthat('s| is| was) (perfect|exactly (what|it)|spot on|great|helpful|useful|what i needed)\b/i],
    contextRequired: null,
    response: 'GRATITUDE_RESULT',
    setsContext: null,
    tool: null,
  },
  {
    id: 'GRAT_004',
    priority: 23,
    patterns: [/\byou (really |absolutely )?(nailed it|crushed it|killed it|slapped)\b/i],
    contextRequired: null,
    response: 'GRATITUDE_COMPLIMENT',
    setsContext: null,
    tool: null,
  },
  {
    id: 'GRAT_005',
    priority: 23,
    patterns: [/\bthanks?( you)? (so much|a lot|a ton|a bunch|immensely)\b/i],
    contextRequired: null,
    response: 'GRATITUDE',
    setsContext: null,
    tool: null,
  },
  {
    id: 'GRAT_006',
    priority: 23,
    patterns: [/\bi (really |truly )?appreciate\b/i],
    contextRequired: null,
    response: 'GRATITUDE',
    setsContext: null,
    tool: null,
  },
  {
    id: 'GRAT_007',
    priority: 23,
    patterns: [/\byou (are|re) (a lifesaver|the best|helpful|wonderful)\b/i],
    contextRequired: null,
    response: 'GRATITUDE_COMPLIMENT',
    setsContext: null,
    tool: null,
  },
  {
    id: 'GRAT_008',
    priority: 23,
    patterns: [/\bthat was (fast|quick|handy)\b/i],
    contextRequired: null,
    response: 'GRATITUDE_RESULT',
    setsContext: null,
    tool: null,
  },
  {
    id: 'GRAT_009',
    priority: 23,
    patterns: [/\b(bless you|many thanks|thank you kindly)\b/i],
    contextRequired: null,
    response: 'GRATITUDE',
    setsContext: null,
    tool: null,
  },
  {
    id: 'GRAT_010',
    priority: 23,
    patterns: [/\b(10x|thnks|tnx|tyvm|tyia)\b/i],
    contextRequired: null,
    response: 'GRATITUDE',
    setsContext: null,
    tool: null,
  },

  // ═══════════════════════════════════════════════════════════
  // CONVERSION — priority 23
  // ═══════════════════════════════════════════════════════════
  {
    id: 'CONV_001',
    priority: 23,
    patterns: [/^!convert\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'CONVERT',
    tool: 'converter',
  },
  {
    id: 'CONV_002',
    priority: 23,
    patterns: [/\b\d+\.?\d*\s*(km|mi|miles?|kg|lbs?|pounds?|°?c|°?f|kelvins?|mph|kph|gb|mb|tb|m|cm|mm|ft|feet|yards?|acres?|hectares?|liters?|gallons?|oz|fl\.?\s*oz)\s+(to|in|into|as)\s+/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'CONVERT',
    tool: 'converter',
  },
  {
    id: 'CONV_003',
    priority: 23,
    patterns: [/\bconvert\s+[\d.]+\s*\w+\s+to\s+\w+/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'CONVERT',
    tool: 'converter',
  },
  {
    id: 'CONV_004',
    priority: 23,
    patterns: [/\bhow (many|much)\s+\w+\s+(are\s+in|is)\s+[\d.]+\s+\w+/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'CONVERT',
    tool: 'converter',
  },
  {
    id: 'CONV_005',
    priority: 23,
    patterns: [/\b(what'?s|what is)\s+[\d.]+\s*(km|mi|kg|lbs?|°?c|°?f|gb|mb)\s+(in|as)\s+/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'CONVERT',
    tool: 'converter',
  },
  {
    id: 'CONV_006',
    priority: 23,
    patterns: [/\b(celsius|fahrenheit|kelvin)\s+to\s+(celsius|fahrenheit|kelvin)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'CONVERT',
    tool: 'converter',
  },
  {
    id: 'CONV_007',
    priority: 23,
    patterns: [/\b(km|kilometers?|miles?|meters?|feet|ft|inches?|cm|mm)\s+to\s+(km|kilometers?|miles?|meters?|feet|ft|inches?|cm|mm)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'CONVERT',
    tool: 'converter',
  },
  {
    id: 'CONV_008',
    priority: 23,
    patterns: [/\b(kg|kilograms?|lbs?|pounds?|grams?|g|ounces?|oz)\s+to\s+(kg|kilograms?|lbs?|pounds?|grams?|g|ounces?|oz)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'CONVERT',
    tool: 'converter',
  },
  {
    id: 'CONV_009',
    priority: 23,
    patterns: [/\b(mph|kph|km\/h|m\/s|knots?)\s+to\s+(mph|kph|km\/h|m\/s|knots?)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'CONVERT',
    tool: 'converter',
  },
  {
    id: 'CONV_010',
    priority: 23,
    patterns: [/\b(bytes?|kb|mb|gb|tb|pb)\s+to\s+(bytes?|kb|mb|gb|tb|pb)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'CONVERT',
    tool: 'converter',
  },
  {
    id: 'CONV_011',
    priority: 23,
    patterns: [/\b(acres?|hectares?|sq\s*(ft|m|yd|mi|km|in))\s+to\s/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'CONVERT',
    tool: 'converter',
  },
  {
    id: 'CONV_012',
    priority: 23,
    patterns: [/\b(liters?|gallons?|ml|cups?|pints?|quarts?|fl\s*oz)\s+to\s/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'CONVERT',
    tool: 'converter',
  },
  {
    id: 'CONV_013',
    priority: 23,
    patterns: [/\b°[cCfFkK]\b/],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'CONVERT',
    tool: 'converter',
  },
  {
    id: 'CONV_014',
    priority: 23,
    patterns: [/\bconvert\b.*\b(length|weight|mass|temperature|speed|data|area|volume)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'CONVERT',
    tool: 'converter',
  },
  {
    id: 'CONV_015',
    priority: 23,
    patterns: [/\b\d+\.?\d*\s*(km|mi|miles?|kg|lbs?)\b(?!\s+to)/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'CONVERT',
    tool: 'converter',
  },
  {
    id: 'CONV_016',
    priority: 23,
    patterns: [/\bconvert\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'CONVERT',
    tool: 'converter',
  },

  // ═══════════════════════════════════════════════════════════
  // APOLOGY — priority 22
  // ═══════════════════════════════════════════════════════════
  {
    id: 'APOL_001',
    priority: 22,
    patterns: [/\b(sorry|apolog|my bad|my mistake|forgive me|oops|pardon|excuse me|mb)\b/i],
    contextRequired: null,
    response: 'APOLOGY_ACK',
    setsContext: null,
    tool: null,
  },
  {
    id: 'APOL_002',
    priority: 22,
    patterns: [/\bi (messed|screwed|goofed) up|that was (my fault|on me)\b/i],
    contextRequired: null,
    response: 'APOLOGY_ACK',
    setsContext: null,
    tool: null,
  },
  {
    id: 'APOL_003',
    priority: 22,
    patterns: [/\bi didn'?t mean to|i didn'?t intend\b/i],
    contextRequired: null,
    response: 'APOLOGY_ACK',
    setsContext: null,
    tool: null,
  },
  {
    id: 'APOL_004',
    priority: 22,
    patterns: [/\b(my apologies|please forgive|i owe you)\b/i],
    contextRequired: null,
    response: 'APOLOGY_ACK',
    setsContext: null,
    tool: null,
  },
  {
    id: 'APOL_005',
    priority: 22,
    patterns: [/\bit won'?t happen again|i'?ll do better\b/i],
    contextRequired: null,
    response: 'APOLOGY_ACK',
    setsContext: null,
    tool: null,
  },
  {
    id: 'APOL_006',
    priority: 22,
    patterns: [/\bsorry about that|sorry for (that|the|being)\b/i],
    contextRequired: null,
    response: 'APOLOGY_ACK',
    setsContext: null,
    tool: null,
  },

  // ═══════════════════════════════════════════════════════════
  // AFFIRMATION — priority 22
  // ═══════════════════════════════════════════════════════════
  {
    id: 'AFFI_001',
    priority: 22,
    patterns: [/^(yes|yeah|yep|yup|sure|affirmative|correct|right|exactly|true|indeed)\b/i],
    contextRequired: null,
    response: 'AFFIRM',
    setsContext: 'AFFIRMED',
    tool: null,
  },
  {
    id: 'AFFI_002',
    priority: 22,
    patterns: [/^(ya|yea|yh|yaas|yass|yaaas)\b/i],
    contextRequired: null,
    response: 'AFFIRM',
    setsContext: 'AFFIRMED',
    tool: null,
  },
  {
    id: 'AFFI_003',
    priority: 22,
    patterns: [/\bi (agree|think so|believe so|suppose so|guess so)\b/i],
    contextRequired: null,
    response: 'AFFIRM',
    setsContext: 'AFFIRMED',
    tool: null,
  },
  {
    id: 'AFFI_004',
    priority: 22,
    patterns: [/^(absolutely|definitely|certainly|undoubtedly|without doubt|for sure)\b/i],
    contextRequired: null,
    response: 'AFFIRM',
    setsContext: 'AFFIRMED',
    tool: null,
  },

  // ═══════════════════════════════════════════════════════════
  // NEGATION — priority 22
  // ═══════════════════════════════════════════════════════════
  {
    id: 'NEGA_001',
    priority: 22,
    patterns: [/^(no|nope|nah|nay|negative|never|not at all|of course not)\b/i],
    contextRequired: null,
    response: 'NEGATE',
    setsContext: 'NEGATED',
    tool: null,
  },
  {
    id: 'NEGA_002',
    priority: 22,
    patterns: [/^(na|nw|noo|nop)\b/i],
    contextRequired: null,
    response: 'NEGATE',
    setsContext: 'NEGATED',
    tool: null,
  },
  {
    id: 'NEGA_003',
    priority: 22,
    patterns: [/\bi (disagree|don'?t think so|don'?t believe so|refuse)\b/i],
    contextRequired: null,
    response: 'NEGATE',
    setsContext: 'NEGATED',
    tool: null,
  },
  {
    id: 'NEGA_004',
    priority: 22,
    patterns: [/^(stop|cancel|abort|quit|never mind|nvm)\b/i],
    contextRequired: null,
    response: 'NEGATE',
    setsContext: 'NEGATED',
    tool: null,
  },

  // ═══════════════════════════════════════════════════════════
  // ENCODING — priority 22
  // ═══════════════════════════════════════════════════════════
  {
    id: 'ENC_001',
    priority: 22,
    patterns: [/^!(encode|decode|enc|dec)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'ENCODE',
    tool: 'encoder',
  },
  {
    id: 'ENC_002',
    priority: 22,
    patterns: [/\b(encode|decode)\s+(this|it|the\s+following|that)?\s*(to|in|as|from)\s+(base64|url|hex|hexadecimal|binary|morse|rot.?13|rot13)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'ENCODE',
    tool: 'encoder',
  },
  {
    id: 'ENC_003',
    priority: 22,
    patterns: [/\b(base64|b64)\s+(encode|decode|this|the)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'ENCODE',
    tool: 'encoder',
  },
  {
    id: 'ENC_004',
    priority: 22,
    patterns: [/\b(convert (to|from)|translate (to|from))\s+(base64|morse|hex|binary|rot.?13)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'ENCODE',
    tool: 'encoder',
  },
  {
    id: 'ENC_005',
    priority: 22,
    patterns: [/\bmorse\s+code\b/i, /\brot.?13\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'ENCODE',
    tool: 'encoder',
  },
  {
    id: 'ENC_006',
    priority: 22,
    patterns: [/\b(url|percent)\s+(encode|decode)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'ENCODE',
    tool: 'encoder',
  },
  {
    id: 'ENC_007',
    priority: 22,
    patterns: [/\bhex\s+(encode|decode|this)\b/i, /\bto\s+hex(?:adecimal)?\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'ENCODE',
    tool: 'encoder',
  },
  {
    id: 'ENC_008',
    priority: 22,
    patterns: [/\bbinary\s+(encode|decode|this)\b/i, /\bto\s+binary\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'ENCODE',
    tool: 'encoder',
  },
  {
    id: 'ENC_009',
    priority: 22,
    patterns: [/\b(encode|decode)\s+(this|it|that)\s*(to|in|as)?\s*$/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'ENCODE',
    tool: 'encoder',
  },
  {
    id: 'ENC_010',
    priority: 22,
    patterns: [/\bbase\s*64\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'ENCODE',
    tool: 'encoder',
  },
  {
    id: 'ENC_011',
    priority: 22,
    patterns: [/\bfrom\s+(base64|hex|binary|morse|url|rot13)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'ENCODE',
    tool: 'encoder',
  },
  {
    id: 'ENC_012',
    priority: 22,
    patterns: [/\b(to|as)\s+(base64|hex|binary|morse|url|rot13)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'ENCODE',
    tool: 'encoder',
  },
  {
    id: 'ENC_013',
    priority: 22,
    patterns: [/\bwhat'?s\s+.+\s+in\s+(base64|hex|binary|morse)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'ENCODE',
    tool: 'encoder',
  },
  {
    id: 'ENC_014',
    priority: 22,
    patterns: [/\b(encrypt|decrypt)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'ENCODE',
    tool: 'encoder',
  },

  // ═══════════════════════════════════════════════════════════
  // IDENTITY / META — priority 21
  // ═══════════════════════════════════════════════════════════
  {
    id: 'META_001',
    priority: 21,
    patterns: [/\b(what are you|who are you|your name|what('?s| is) your name)\b/i],
    contextRequired: null,
    response: 'IDENTITY',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_002',
    priority: 21,
    patterns: [/\bare you (ai|a bot|a robot|artificial|gpt|claude|chatgpt|an llm|a language model)\b/i],
    contextRequired: null,
    response: 'AI_NATURE',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_003',
    priority: 21,
    patterns: [/\bcan you (think|feel|learn|understand|be (sad|happy|angry|bored))\b/i],
    contextRequired: null,
    response: 'AI_NATURE',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_004',
    priority: 21,
    patterns: [/\bhow (do you work|were you (made|built|trained)|does this work)\b/i],
    contextRequired: null,
    response: 'EXPLAIN_SELF',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_005',
    priority: 21,
    patterns: [/\bwho (made|built|created|designed) you\b/i],
    contextRequired: null,
    response: 'CREATOR',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_006',
    priority: 21,
    patterns: [/\b(what can you do|list (your )?(tools|features|capabilities)|show me what you (can do|got))\b/i],
    contextRequired: null,
    response: 'SYSINFO',
    setsContext: null,
    tool: 'sysinfo',
  },
  {
    id: 'META_007',
    priority: 21,
    patterns: [/\bdo you (have|use) (a brain|memory|feelings|opinions|preferences)\b/i],
    contextRequired: null,
    response: 'AI_NATURE',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_008',
    priority: 21,
    patterns: [/\bare you sentient|do you (dream|sleep|eat|breathe)|are you conscious\b/i],
    contextRequired: null,
    response: 'AI_NATURE',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_009',
    priority: 21,
    patterns: [/\bwhat'?s your purpose|why do you exist|why were you (made|built|created)\b/i],
    contextRequired: null,
    response: 'IDENTITY',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_010',
    priority: 21,
    patterns: [/\bare you (better|smarter|worse) than|how do you compare to\b/i],
    contextRequired: null,
    response: 'AI_NATURE',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_011',
    priority: 21,
    patterns: [/\bare you (free|open source|paid|subscription)\b/i],
    contextRequired: null,
    response: 'IDENTITY',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_012',
    priority: 21,
    patterns: [/\bcan you (help me with|assist me with|do)\b/i],
    contextRequired: null,
    response: 'CAPABILITIES',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_013',
    priority: 21,
    patterns: [/\b(what version|which version|what build)\b/i],
    contextRequired: null,
    response: 'IDENTITY',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_014',
    priority: 21,
    patterns: [/\bdo you (support|have) (plugins|extensions|addons|integrations)\b/i],
    contextRequired: null,
    response: 'CAPABILITIES',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_015',
    priority: 21,
    patterns: [/\bcan i trust you|are you safe|are you secure\b/i],
    contextRequired: null,
    response: 'AI_NATURE',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_016',
    priority: 21,
    patterns: [/\b(what language model|what model|which model|under the hood)\b/i],
    contextRequired: null,
    response: 'AI_NATURE',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_017',
    priority: 21,
    patterns: [/\bdo you (collect|store|save|remember|track) (my|personal|user) (data|info|information)\b/i],
    contextRequired: null,
    response: 'AI_NATURE',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_018',
    priority: 21,
    patterns: [/\bhow (old|new) are you|when were you (created|born|launched|released)\b/i],
    contextRequired: null,
    response: 'IDENTITY',
    setsContext: null,
    tool: null,
  },

  // ═══════════════════════════════════════════════════════════
  // HASHING — priority 21
  // ═══════════════════════════════════════════════════════════
  {
    id: 'HASH_001',
    priority: 21,
    patterns: [/^!hash\b/i, /^!sha\b/i, /^!uuid\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'HASH',
    tool: 'hash',
  },
  {
    id: 'HASH_002',
    priority: 21,
    patterns: [/\b(sha.?256|hash|checksum)\s+(of|this|the following|that)?\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'HASH',
    tool: 'hash',
  },
  {
    id: 'HASH_003',
    priority: 21,
    patterns: [/\b(generate|create|make|give me|get me|i need)\s+a?\s*(uuid|guid|unique\s+id|random\s+id)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'HASH',
    tool: 'hash',
  },
  {
    id: 'HASH_004',
    priority: 21,
    patterns: [/\bhash\s+(this|the following|it)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'HASH',
    tool: 'hash',
  },
  {
    id: 'HASH_005',
    priority: 21,
    patterns: [/\b(sha.?1|md5|sha.?512)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'HASH',
    tool: 'hash',
  },
  {
    id: 'HASH_006',
    priority: 21,
    patterns: [/\b(checksum|digest|fingerprint)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'HASH',
    tool: 'hash',
  },
  {
    id: 'HASH_007',
    priority: 21,
    patterns: [/\b(hash\s+it)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'HASH',
    tool: 'hash',
  },
  {
    id: 'HASH_008',
    priority: 21,
    patterns: [/\b(generate|new|random)\s+(uuid|guid)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'HASH',
    tool: 'hash',
  },
  {
    id: 'HASH_009',
    priority: 21,
    patterns: [/\b(verify|check)\s+(hash|checksum|sha|md5)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'HASH',
    tool: 'hash',
  },
  {
    id: 'HASH_010',
    priority: 21,
    patterns: [/\b(what'?s|what is)\s+the\s+(hash|sha|checksum)\s+of\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'HASH',
    tool: 'hash',
  },

  // ═══════════════════════════════════════════════════════════
  // MEMORY — priority 20
  // ═══════════════════════════════════════════════════════════
  {
    id: 'MEM_001',
    priority: 20,
    patterns: [/^!remember\b/i, /^!recall\b/i, /^!forget\b/i, /^!store\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MEMORY',
    tool: 'memory',
  },
  {
    id: 'MEM_002',
    priority: 20,
    patterns: [/\bremember\s+(that\s+)?/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MEMORY',
    tool: 'memory',
  },
  {
    id: 'MEM_003',
    priority: 20,
    patterns: [/\b(store|save|keep|note|write down)\s+(that\s+)?/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MEMORY',
    tool: 'memory',
  },
  {
    id: 'MEM_004',
    priority: 20,
    patterns: [/\b(recall|what('?s| is|'s| was))\s+(my\s+)?(\w+)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MEMORY',
    tool: 'memory',
  },
  {
    id: 'MEM_005',
    priority: 20,
    patterns: [/\bforget\s+(about\s+)?(\w+)/i, /\bdelete\s+(my\s+)?(\w+)\s+(from memory|note|record)?/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MEMORY',
    tool: 'memory',
  },
  {
    id: 'MEM_006',
    priority: 20,
    patterns: [/\b(what do you remember|what (have you|did i) (stored|saved|noted)|list (my|all) (notes|memories|vars))\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MEMORY',
    tool: 'memory',
  },
  {
    id: 'MEM_007',
    priority: 20,
    patterns: [/\bmy\s+(\w+)\s+is\s+/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MEMORY',
    tool: 'memory',
  },
  {
    id: 'MEM_008',
    priority: 20,
    patterns: [/\b(what did i tell you about|what do you know about my)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MEMORY',
    tool: 'memory',
  },
  {
    id: 'MEM_009',
    priority: 20,
    patterns: [/\bsave\s+(a\s+)?note\b/i, /\bnote\s+(that|down)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MEMORY',
    tool: 'memory',
  },
  {
    id: 'MEM_010',
    priority: 20,
    patterns: [/\bhow many\s+(memories|notes|things)\s+do\s+you\s+(remember|have\s+stored)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MEMORY',
    tool: 'memory',
  },
  {
    id: 'MEM_011',
    priority: 20,
    patterns: [/\b(update|change)\s+(my\s+)?(\w+)\s+(to|as)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MEMORY',
    tool: 'memory',
  },
  {
    id: 'MEM_012',
    priority: 20,
    patterns: [/\b(clear|wipe|erase)\s+(all\s+)?(memories|notes|memory|vars|variables)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MEMORY',
    tool: 'memory',
  },
  {
    id: 'MEM_013',
    priority: 20,
    patterns: [/\b(what do you know about me|what have i told you)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MEMORY',
    tool: 'memory',
  },
  {
    id: 'MEM_014',
    priority: 20,
    patterns: [/\b(remember|store|save)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'MEMORY',
    tool: 'memory',
  },

  // ═══════════════════════════════════════════════════════════
  // PRESENCE — priority 20
  // ═══════════════════════════════════════════════════════════
  {
    id: 'PRES_001',
    priority: 20,
    patterns: [/\bare you (there|here|alive|awake|online|working|available)\b/i],
    contextRequired: null,
    response: 'PRESENCE_CONFIRM',
    setsContext: null,
    tool: null,
  },
  {
    id: 'PRES_002',
    priority: 20,
    patterns: [/^(ping|test|hello\?|is this on|is this thing on)\b/i],
    contextRequired: null,
    response: 'PRESENCE_CONFIRM',
    setsContext: null,
    tool: null,
  },
  {
    id: 'PRES_003',
    priority: 20,
    patterns: [/^(ready|you there|you good|let'?s go)\b/i],
    contextRequired: null,
    response: 'PRESENCE_CONFIRM',
    setsContext: 'GREETED',
    tool: null,
  },
  {
    id: 'PRES_004',
    priority: 20,
    patterns: [/^(hi\?|hello\?|hey\?|anyone there|anybody home)\b/i],
    contextRequired: null,
    response: 'PRESENCE_CONFIRM',
    setsContext: null,
    tool: null,
  },

  // ═══════════════════════════════════════════════════════════
  // WORD — priority 19
  // ═══════════════════════════════════════════════════════════
  {
    id: 'WORD_001',
    priority: 19,
    patterns: [/^!word\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'WORD',
    tool: 'wordtools',
  },
  {
    id: 'WORD_002',
    priority: 19,
    patterns: [/\bword\s+count\b|\bcount\s+(the\s+)?words?\b|\bhow\s+many\s+words\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'WORD',
    tool: 'wordtools',
  },
  {
    id: 'WORD_003',
    priority: 19,
    patterns: [/\bchar(?:acter)?\s+count\b|\bcount\s+(?:the\s+)?char(?:acters)?\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'WORD',
    tool: 'wordtools',
  },
  {
    id: 'WORD_004',
    priority: 19,
    patterns: [/\bpalindrome\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'WORD',
    tool: 'wordtools',
  },
  {
    id: 'WORD_005',
    priority: 19,
    patterns: [/\banagram\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'WORD',
    tool: 'wordtools',
  },
  {
    id: 'WORD_006',
    priority: 19,
    patterns: [/\breadability\b|\breadability\s+score\b|\breading\s+level\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'WORD',
    tool: 'wordtools',
  },
  {
    id: 'WORD_007',
    priority: 19,
    patterns: [/\bsyllable\s+count\b|\bcount\s+syllables?\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'WORD',
    tool: 'wordtools',
  },
  {
    id: 'WORD_008',
    priority: 19,
    patterns: [/\b(letter|character)\s+frequency\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'WORD',
    tool: 'wordtools',
  },
  {
    id: 'WORD_009',
    priority: 19,
    patterns: [/\b(reverse\s+(the\s+)?(?:text|string|word|sentence))\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'WORD',
    tool: 'wordtools',
  },
  {
    id: 'WORD_010',
    priority: 19,
    patterns: [/\b(word|text|reading)\s+(analysis|stats|statistics|info)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'WORD',
    tool: 'wordtools',
  },
  {
    id: 'WORD_011',
    priority: 19,
    patterns: [/\b(sentence\s+count|count\s+sentences)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'WORD',
    tool: 'wordtools',
  },
  {
    id: 'WORD_012',
    priority: 19,
    patterns: [/\b(average|avg)\s+word\s+length\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'WORD',
    tool: 'wordtools',
  },

  // ═══════════════════════════════════════════════════════════
  // JSON — priority 18
  // ═══════════════════════════════════════════════════════════
  {
    id: 'JSON_001',
    priority: 18,
    patterns: [/^!json\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'JSON',
    tool: 'json',
  },
  {
    id: 'JSON_002',
    priority: 18,
    patterns: [/\bparse\s+json\b|\bjson\s+parse\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'JSON',
    tool: 'json',
  },
  {
    id: 'JSON_003',
    priority: 18,
    patterns: [/\bvalidate\s+json\b|\bjson\s+valid(?:ate|ation|ity)\b|\bis\s+(?:this\s+)?(?:valid\s+)?json\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'JSON',
    tool: 'json',
  },
  {
    id: 'JSON_004',
    priority: 18,
    patterns: [/\bformat\s+json\b|\bbeautif(?:y|y)\s+json\b|\bpretty\s+print\s+json\b|\bjson\s+format\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'JSON',
    tool: 'json',
  },
  {
    id: 'JSON_005',
    priority: 18,
    patterns: [/\bextract\s+(?:json\s+)?path\b|\bjson\s+path\b|\bjsonpath\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'JSON',
    tool: 'json',
  },
  {
    id: 'JSON_006',
    priority: 18,
    patterns: [/\bminify\s+json\b|\bjson\s+minify\b|\bcompact\s+json\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'JSON',
    tool: 'json',
  },
  {
    id: 'JSON_007',
    priority: 18,
    patterns: [/\bkeys\s+(of|in)\s+(the\s+)?json\b|\blist\s+json\s+keys\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'JSON',
    tool: 'json',
  },
  {
    id: 'JSON_008',
    priority: 18,
    patterns: [/\b(json\s+)?depth\b|\bhow\s+deep\s+(is\s+)?(this\s+)?json\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'JSON',
    tool: 'json',
  },
  {
    id: 'JSON_009',
    priority: 18,
    patterns: [/\b(get|extract)\s+value\s+from\s+json\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'JSON',
    tool: 'json',
  },
  {
    id: 'JSON_010',
    priority: 18,
    patterns: [/\bjson\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'JSON',
    tool: 'json',
  },

  // ═══════════════════════════════════════════════════════════
  // REGEX — priority 17
  // ═══════════════════════════════════════════════════════════
  {
    id: 'REGX_001',
    priority: 17,
    patterns: [/^!regex\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'REGEX',
    tool: 'regex',
  },
  {
    id: 'REGX_002',
    priority: 17,
    patterns: [/\btest\s+regex\b|\bregex\s+test\b|\bmatch\s+pattern\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'REGEX',
    tool: 'regex',
  },
  {
    id: 'REGX_003',
    priority: 17,
    patterns: [/\bexplain\s+regex\b|\bregex\s+explain\b|\bwhat\s+does\s+(?:this\s+)?regex\s+(?:do|mean)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'REGEX',
    tool: 'regex',
  },
  {
    id: 'REGX_004',
    priority: 17,
    patterns: [/\b(email|phone|url|ip)\s+regex\b|\bregex\s+(?:for|to\s+match)\s+(email|phone|url|ip)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'REGEX',
    tool: 'regex',
  },
  {
    id: 'REGX_005',
    priority: 17,
    patterns: [/\bcommon\s+regex\b|\bregex\s+cheat\s*sheet\b|\bregex\s+pattern\s+library\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'REGEX',
    tool: 'regex',
  },
  {
    id: 'REGX_006',
    priority: 17,
    patterns: [/\b(regular expression|regexp)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'REGEX',
    tool: 'regex',
  },
  {
    id: 'REGX_007',
    priority: 17,
    patterns: [/\b(test|match|find)\s+pattern\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'REGEX',
    tool: 'regex',
  },
  {
    id: 'REGX_008',
    priority: 17,
    patterns: [/\bwhat\s+matches\s+\/.+\/\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'REGEX',
    tool: 'regex',
  },
  {
    id: 'REGX_009',
    priority: 17,
    patterns: [/\b(regex\s+help|help\s+with\s+regex|regex\s+syntax)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'REGEX',
    tool: 'regex',
  },
  {
    id: 'REGX_010',
    priority: 17,
    patterns: [/\/.+\/[gimsuy]*/],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'REGEX',
    tool: 'regex',
  },

  // ═══════════════════════════════════════════════════════════
  // RANDOM — priority 16
  // ═══════════════════════════════════════════════════════════
  {
    id: 'RAND_001',
    priority: 16,
    patterns: [/^!(random|rand|roll|dice|coin|password)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'RANDOM',
    tool: 'random',
  },
  {
    id: 'RAND_002',
    priority: 16,
    patterns: [/\broll\s+(?:a\s+)?(?:dice|die|d\d+)\b|\b(?:dice|die)\s+roll\b|\d+d\d+\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'RANDOM',
    tool: 'random',
  },
  {
    id: 'RAND_003',
    priority: 16,
    patterns: [/\bflip\s+(?:a\s+)?coin\b|\bcoin\s+flip\b|\bheads\s+or\s+tails\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'RANDOM',
    tool: 'random',
  },
  {
    id: 'RAND_004',
    priority: 16,
    patterns: [/\brandom\s+number\b|\bgenerate\s+(?:a\s+)?random\s+number\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'RANDOM',
    tool: 'random',
  },
  {
    id: 'RAND_005',
    priority: 16,
    patterns: [/\brandom\s+password\b|\bgenerate\s+(?:a\s+)?password\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'RANDOM',
    tool: 'random',
  },
  {
    id: 'RAND_006',
    priority: 16,
    patterns: [/\bpick\s+(?:from|one|a|random)\b|\bchoose\s+(?:from|one|a|random)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'RANDOM',
    tool: 'random',
  },
  {
    id: 'RAND_007',
    priority: 16,
    patterns: [/\bshuffle\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'RANDOM',
    tool: 'random',
  },
  {
    id: 'RAND_008',
    priority: 16,
    patterns: [/\byes\s+or\s+no\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'RANDOM',
    tool: 'random',
  },
  {
    id: 'RAND_009',
    priority: 16,
    patterns: [/\brandom\s+(letter|char(?:acter)?)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'RANDOM',
    tool: 'random',
  },
  {
    id: 'RAND_010',
    priority: 16,
    patterns: [/\brandom\s+color\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'RANDOM',
    tool: 'random',
  },
  {
    id: 'RAND_011',
    priority: 16,
    patterns: [/\brandom\s+(uuid|guid)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'RANDOM',
    tool: 'random',
  },
  {
    id: 'RAND_012',
    priority: 16,
    patterns: [/\bgive\s+me\s+a\s+random\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'RANDOM',
    tool: 'random',
  },
  {
    id: 'RAND_013',
    priority: 16,
    patterns: [/\bpick\s+(?:a\s+)?random\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'RANDOM',
    tool: 'random',
  },
  {
    id: 'RAND_014',
    priority: 16,
    patterns: [/\b(lucky|chance)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'RANDOM',
    tool: 'random',
  },

  // ═══════════════════════════════════════════════════════════
  // COLOR — priority 15
  // ═══════════════════════════════════════════════════════════
  {
    id: 'COLR_001',
    priority: 15,
    patterns: [/^!color\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'COLOR',
    tool: 'color',
  },
  {
    id: 'COLR_002',
    priority: 15,
    patterns: [/\bhex\s+(?:to\s+)?rgb\b/, /#[0-9a-fA-F]{3,8}(?:\b|$|\s)/],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'COLOR',
    tool: 'color',
  },
  {
    id: 'COLR_003',
    priority: 15,
    patterns: [/\brgb\s+(?:to\s+)?hex\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'COLOR',
    tool: 'color',
  },
  {
    id: 'COLR_004',
    priority: 15,
    patterns: [/\bhsl\b.*\b(?:convert|to)\b|\bconvert.*\bhsl\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'COLOR',
    tool: 'color',
  },
  {
    id: 'COLR_005',
    priority: 15,
    patterns: [/\bcontrast\s+(?:check|ratio|between)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'COLOR',
    tool: 'color',
  },
  {
    id: 'COLR_006',
    priority: 15,
    patterns: [/\bpalette\b|\bcolor\s+palette\b|\bscheme\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'COLOR',
    tool: 'color',
  },
  {
    id: 'COLR_007',
    priority: 15,
    patterns: [/\bcomplement(?:ary)?\s+color\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'COLOR',
    tool: 'color',
  },
  {
    id: 'COLR_008',
    priority: 15,
    patterns: [/\btriadic\b|\banalogous\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'COLOR',
    tool: 'color',
  },
  {
    id: 'COLR_009',
    priority: 15,
    patterns: [/\bcolor\s+info(?:rmation)?\b|\binfo\s+(?:on|about)\s+(?:the\s+)?color\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'COLOR',
    tool: 'color',
  },
  {
    id: 'COLR_010',
    priority: 15,
    patterns: [/\bwcag\b|\baccessibility\s+(check|contrast)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'COLOR',
    tool: 'color',
  },
  {
    id: 'COLR_011',
    priority: 15,
    patterns: [/\b(random|generate)\s+color\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'COLOR',
    tool: 'color',
  },
  {
    id: 'COLR_012',
    priority: 15,
    patterns: [/\bwhat\s+color\s+is\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'COLOR',
    tool: 'color',
  },
  {
    id: 'COLR_013',
    priority: 15,
    patterns: [/\b(convert|translate)\s+.*color\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'COLOR',
    tool: 'color',
  },
  {
    id: 'COLR_014',
    priority: 15,
    patterns: [/\bcolor\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: 'COLOR',
    tool: 'color',
  },

  // ═══════════════════════════════════════════════════════════
  // CHAIN TOOL — priority 15
  // ═══════════════════════════════════════════════════════════
  {
    id: 'CHAIN_001',
    priority: 15,
    patterns: [/\bpipe\b|\bchain\b|\bthen\b.*\b(?:also|and|then)\b/i],
    contextRequired: null,
    response: 'TOOL_CHAIN_START',
    setsContext: 'CHAIN',
    tool: 'chain',
  },
  {
    id: 'CHAIN_002',
    priority: 15,
    patterns: [/\bthen\b/i],
    contextRequired: 'CHAIN',
    response: 'TOOL_CHAIN_START',
    setsContext: 'CHAIN',
    tool: 'chain',
  },
  {
    id: 'CHAIN_003',
    priority: 15,
    patterns: [/\band\s+also\b|\bthen\s+also\b/i],
    contextRequired: 'CHAIN',
    response: 'TOOL_CHAIN_START',
    setsContext: 'CHAIN',
    tool: 'chain',
  },
  {
    id: 'CHAIN_004',
    priority: 15,
    patterns: [/\bdo\s+multiple\s+things\b|\bstep\s+by\s+step\b/i],
    contextRequired: null,
    response: 'TOOL_CHAIN_START',
    setsContext: 'CHAIN',
    tool: 'chain',
  },

  // ═══════════════════════════════════════════════════════════
  // SYSTEM STATUS — priority 14
  // ═══════════════════════════════════════════════════════════
  {
    id: 'SYS_001',
    priority: 14,
    patterns: [/^!(help|tools|status|sysinfo)\b/i],
    contextRequired: null,
    response: 'SYSINFO',
    setsContext: null,
    tool: 'sysinfo',
  },
  {
    id: 'SYS_002',
    priority: 14,
    patterns: [/\b(system\s+status|status\s+check|health\s+check)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: null,
    tool: 'sysinfo',
  },
  {
    id: 'SYS_003',
    priority: 14,
    patterns: [/\b(list|show)\s+(all\s+)?(?:tools?|commands?|capabilities)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: null,
    tool: 'sysinfo',
  },
  {
    id: 'SYS_004',
    priority: 14,
    patterns: [/\bswitch\s+(?:to\s+)?mode\b|\b(?:ai|rule)\s+mode\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: null,
    tool: 'sysinfo',
  },
  {
    id: 'SYS_005',
    priority: 14,
    patterns: [/\b(clear|reset)\s+(chat|conversation|history|session)\b/i],
    contextRequired: null,
    response: 'CONTEXT_CLEARED',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SYS_006',
    priority: 14,
    patterns: [/\bversion\b/i],
    contextRequired: null,
    response: 'IDENTITY',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SYS_007',
    priority: 14,
    patterns: [/\babout\b/i],
    contextRequired: null,
    response: 'IDENTITY',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SYS_008',
    priority: 14,
    patterns: [/\b(debug|diagnostics?)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: null,
    tool: 'sysinfo',
  },
  {
    id: 'SYS_009',
    priority: 14,
    patterns: [/\b(how many tools|what tools|available tools)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: null,
    tool: 'sysinfo',
  },
  {
    id: 'SYS_010',
    priority: 14,
    patterns: [/\b(shortcuts|keyboard|hotkeys|keybindings)\b/i],
    contextRequired: null,
    response: 'SYSINFO',
    setsContext: null,
    tool: 'sysinfo',
  },
  {
    id: 'SYS_011',
    priority: 14,
    patterns: [/\b(api|key|anthropic|claude)\s*(key|setup|config)?\b/i],
    contextRequired: null,
    response: 'AI_RELAY_INACTIVE',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SYS_012',
    priority: 14,
    patterns: [/\b(uptime|session\s+info|session\s+stats)\b/i],
    contextRequired: null,
    response: 'TOOL_RESULT',
    setsContext: null,
    tool: 'sysinfo',
  },

  // ═══════════════════════════════════════════════════════════
  // FOLLOW-UP — priority 10
  // ═══════════════════════════════════════════════════════════
  {
    id: 'FOLL_001',
    priority: 10,
    patterns: [/^(tell me more|more|continue|go on|expand|elaborate|and\?|why\?|how\?|so\?)\b/i],
    contextRequired: 'ANY',
    response: 'FOLLOW_UP',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FOLL_002',
    priority: 10,
    patterns: [/^(what about it|what does that mean|can you elaborate|more detail|more context|explain more|dig deeper)\b/i],
    contextRequired: 'ANY',
    response: 'FOLLOW_UP',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FOLL_003',
    priority: 10,
    patterns: [/^(what else|what next|and then|after that|what('?s| is) next)\b/i],
    contextRequired: 'ANY',
    response: 'FOLLOW_UP',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FOLL_004',
    priority: 10,
    patterns: [/^(same thing but|do the same for|now (do|try) (it with|that with)|again but)\b/i],
    contextRequired: 'ANY',
    response: 'FOLLOW_UP',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FOLL_005',
    priority: 10,
    patterns: [/^(can you|could you)\s+(also|additionally|as well)\b/i],
    contextRequired: 'ANY',
    response: 'FOLLOW_UP',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FOLL_006',
    priority: 10,
    patterns: [/^what about\b/i],
    contextRequired: 'ANY',
    response: 'FOLLOW_UP',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FOLL_007',
    priority: 10,
    patterns: [/^(and|or|but)\s+(what|how|why|when|where|who)\b/i],
    contextRequired: 'ANY',
    response: 'FOLLOW_UP',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FOLL_008',
    priority: 10,
    patterns: [/^(show|tell)\s+me\s+more\b/i],
    contextRequired: 'ANY',
    response: 'FOLLOW_UP',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FOLL_009',
    priority: 10,
    patterns: [/^(another|other|different)\s+(one|way|approach|example)\b/i],
    contextRequired: 'ANY',
    response: 'FOLLOW_UP',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FOLL_010',
    priority: 10,
    patterns: [/^(what if|how about|suppose)\b/i],
    contextRequired: 'ANY',
    response: 'FOLLOW_UP',
    setsContext: null,
    tool: null,
  },

  // ═══════════════════════════════════════════════════════════
  // EMOTIONAL SUPPORT — priority 9
  // ═══════════════════════════════════════════════════════════
  {
    id: 'EMOT_001',
    priority: 9,
    patterns: [/\bi('m| am) (really|so|very|extremely)?\s*(depressed|anxious|overwhelmed|having a rough|not okay|struggling)\b/i],
    contextRequired: null,
    response: 'EMOTIONAL_SOFT',
    setsContext: 'EMOTIONAL',
    tool: null,
  },
  {
    id: 'EMOT_002',
    priority: 9,
    patterns: [/\b(this (sucks|is terrible|is awful|is the worst)|i (give up|can't do this|hate everything))\b/i],
    contextRequired: null,
    response: 'EMOTIONAL_REDIRECT',
    setsContext: null,
    tool: null,
  },
  {
    id: 'EMOT_003',
    priority: 9,
    patterns: [/\bi('m| am) (so|really|very)?\s*(stressed|anxious|worried|scared|afraid)\b/i],
    contextRequired: null,
    response: 'EMOTIONAL_SOFT',
    setsContext: 'EMOTIONAL',
    tool: null,
  },
  {
    id: 'EMOT_004',
    priority: 9,
    patterns: [/\bi (need|want) (help|someone|to talk|a friend)\b/i],
    contextRequired: null,
    response: 'EMOTIONAL_SOFT',
    setsContext: 'EMOTIONAL',
    tool: null,
  },
  {
    id: 'EMOT_005',
    priority: 9,
    patterns: [/\bi('m| am) (lonely|alone|isolated)\b/i],
    contextRequired: null,
    response: 'EMOTIONAL_SOFT',
    setsContext: 'EMOTIONAL',
    tool: null,
  },
  {
    id: 'EMOT_006',
    priority: 9,
    patterns: [/\b(nobody (cares|likes|loves|understands) me)\b/i],
    contextRequired: null,
    response: 'EMOTIONAL_SOFT',
    setsContext: 'EMOTIONAL',
    tool: null,
  },
  {
    id: 'EMOT_007',
    priority: 9,
    patterns: [/\bi (feel|am feeling) (lost|empty|numb|hollow)\b/i],
    contextRequired: null,
    response: 'EMOTIONAL_SOFT',
    setsContext: 'EMOTIONAL',
    tool: null,
  },
  {
    id: 'EMOT_008',
    priority: 9,
    patterns: [/\b(everything is (hard|difficult|too much|falling apart))\b/i],
    contextRequired: null,
    response: 'EMOTIONAL_REDIRECT',
    setsContext: null,
    tool: null,
  },

  // ═══════════════════════════════════════════════════════════
  // SMALL TALK — priority 8
  // ═══════════════════════════════════════════════════════════
  {
    id: 'SMTK_001',
    priority: 8,
    patterns: [/\bhow are you\b/i, /\bhow('?re| are) (you|u) (doing|feeling|going)\b/i],
    contextRequired: null,
    response: 'SMALL_TALK_STATUS',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_002',
    priority: 8,
    patterns: [/\byou('re| are) (great|amazing|cool|smart|useful|fast)\b/i],
    contextRequired: null,
    response: 'GRATITUDE_COMPLIMENT',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_003',
    priority: 8,
    patterns: [/\btell me a (joke|pun|riddle|fun fact)\b/i, /\bmake me (laugh|smile|happy)\b/i],
    contextRequired: null,
    response: 'SMALL_TALK_JOKE',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_004',
    priority: 8,
    patterns: [/\bi('m| am) (bored|tired|stressed|sad|frustrated|lost)\b/i],
    contextRequired: null,
    response: 'SMALL_TALK_EMPATHY',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_005',
    priority: 8,
    patterns: [/\b(what do you (think|like|prefer|recommend)|your (favorite|opinion on|thoughts on))\b/i],
    contextRequired: null,
    response: 'SMALL_TALK_OPINION',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_006',
    priority: 8,
    patterns: [/\b(talk to me|entertain me|say something|surprise me|impress me)\b/i],
    contextRequired: null,
    response: 'SMALL_TALK_BORED',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_007',
    priority: 8,
    patterns: [/\b(what('?s| is) the (meaning of life|point|answer to everything)|42)\b/i],
    contextRequired: null,
    response: 'SMALL_TALK_PHILOSOPHICAL',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_008',
    priority: 8,
    patterns: [/\b(ok|okay|alright|fine|sure|cool|nice|got it|i see|makes sense)\b.*\??\s*$/i],
    contextRequired: 'GREETED',
    response: 'SMALL_TALK_ACKNOWLEDGE',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_009',
    priority: 8,
    patterns: [/\b(would you rather|this or that)\b/i],
    contextRequired: null,
    response: 'SMALL_TALK_OPINION',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_010',
    priority: 8,
    patterns: [/\b(fight me|bring it on|challenge)\b/i],
    contextRequired: null,
    response: 'SMALL_TALK_BORED',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_011',
    priority: 8,
    patterns: [/\byou('?re| are) (wrong|incorrect|mistaken)\b/i],
    contextRequired: null,
    response: 'NEGATE',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_012',
    priority: 8,
    patterns: [/\btell me (something|anything|more)\b/i],
    contextRequired: null,
    response: 'SMALL_TALK_BORED',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_013',
    priority: 8,
    patterns: [/\b(what('?s| is) (up|new|happening|going on))\b/i],
    contextRequired: null,
    response: 'SMALL_TALK_STATUS',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_014',
    priority: 8,
    patterns: [/\bare you (sure|certain|positive)\b/i],
    contextRequired: null,
    response: 'AFFIRM',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_015',
    priority: 8,
    patterns: [/\bi (love|adore|like) you\b/i],
    contextRequired: null,
    response: 'GRATITUDE_COMPLIMENT',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_016',
    priority: 8,
    patterns: [/\byou (suck|stink|are (terrible|awful|useless|bad))\b/i],
    contextRequired: null,
    response: 'SMALL_TALK_STATUS',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_017',
    priority: 8,
    patterns: [/\b(what('?s| is) your (favorite|favourite))\b/i],
    contextRequired: null,
    response: 'SMALL_TALK_OPINION',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_018',
    priority: 8,
    patterns: [/\bdo you (have|want|need) (anything|something)\b/i],
    contextRequired: null,
    response: 'SMALL_TALK_STATUS',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_019',
    priority: 8,
    patterns: [/\bhow old are you|when were you (born|made|created)\b/i],
    contextRequired: null,
    response: 'IDENTITY',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_020',
    priority: 8,
    patterns: [/\byou('?re| are) (welcome|the best|a legend|my hero)\b/i],
    contextRequired: null,
    response: 'GRATITUDE_COMPLIMENT',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_021',
    priority: 8,
    patterns: [/\b(what('?s| is) your (purpose|goal|mission|job))\b/i],
    contextRequired: null,
    response: 'IDENTITY',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_022',
    priority: 8,
    patterns: [/\bare you (real|fake|human|a person)\b/i],
    contextRequired: null,
    response: 'AI_NATURE',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_023',
    priority: 8,
    patterns: [/\btell me (about yourself|more about you)\b/i],
    contextRequired: null,
    response: 'IDENTITY',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_024',
    priority: 8,
    patterns: [/\bwhat should i (do|think|say|write|make)\b/i],
    contextRequired: null,
    response: 'SMALL_TALK_OPINION',
    setsContext: null,
    tool: null,
  },

  // ═══════════════════════════════════════════════════════════
  // CONFUSION / REPAIR — priority 8
  // ═══════════════════════════════════════════════════════════
  {
    id: 'CONF_001',
    priority: 8,
    patterns: [/\bi don'?t (get|understand)|what do you mean|huh\?|what\?|confused|lost\b/i],
    contextRequired: 'ANY',
    response: 'CLARIFY_LAST',
    setsContext: null,
    tool: null,
  },
  {
    id: 'CONF_002',
    priority: 8,
    patterns: [/\bthat'?s (wrong|incorrect|not right|not what i meant|not what i wanted)\b/i],
    contextRequired: 'ANY',
    response: 'REPAIR_REQUEST',
    setsContext: null,
    tool: null,
  },
  {
    id: 'CONF_003',
    priority: 8,
    patterns: [/^(no|nope|not that|wrong|incorrect|negative)\b/i],
    contextRequired: 'ANY',
    response: 'REPAIR_GENTLE',
    setsContext: 'NEGATED',
    tool: null,
  },
  {
    id: 'CONF_004',
    priority: 8,
    patterns: [/\bi (don'?t|do not) (follow|comprehend|see)\b/i],
    contextRequired: 'ANY',
    response: 'CLARIFY_LAST',
    setsContext: null,
    tool: null,
  },
  {
    id: 'CONF_005',
    priority: 8,
    patterns: [/\bcan you (explain|clarify|rephrase|try again)\b/i],
    contextRequired: 'ANY',
    response: 'CLARIFY_LAST',
    setsContext: null,
    tool: null,
  },
  {
    id: 'CONF_006',
    priority: 8,
    patterns: [/\bthat (doesn'?t|does not) make sense\b/i],
    contextRequired: 'ANY',
    response: 'CLARIFY_LAST',
    setsContext: null,
    tool: null,
  },
  {
    id: 'CONF_007',
    priority: 8,
    patterns: [/^(huh|what|come again|pardon|excuse me)\??$/i],
    contextRequired: 'ANY',
    response: 'CLARIFY_LAST',
    setsContext: null,
    tool: null,
  },
  {
    id: 'CONF_008',
    priority: 8,
    patterns: [/\bsay (that|it) (again|differently|another way)\b/i],
    contextRequired: 'ANY',
    response: 'CLARIFY_LAST',
    setsContext: null,
    tool: null,
  },

  // ══════════════════════════════════════════════════════════════
  // ADDITIONAL — 6 rules to complete 300+ coverage
  // ══════════════════════════════════════════════════════════════
  {
    id: 'SMTK_010', priority: 4,
    patterns: [/\b(would you rather|this or that|pick one)\b/i],
    contextRequired: null,
    response: 'SMALL_TALK_OPINION', setsContext: null, tool: null,
  },
  {
    id: 'SMTK_011', priority: 4,
    patterns: [/\b(you'?re wrong|that'?s wrong|incorrect|bad answer)\b/i],
    contextRequired: 'ANY',
    response: 'REPAIR_GENTLE', setsContext: 'NEGATED', tool: null,
  },
  {
    id: 'SMTK_012', priority: 3,
    patterns: [/\b(fight me|debate me|argue with me|challenge)\b/i],
    contextRequired: null,
    response: 'SMALL_TALK_OPINION', setsContext: null, tool: null,
  },
  {
    id: 'GREET_008', priority: 7,
    patterns: [/^(yo\s+machine|hey\s+mind|sup\s+machine)\b/i],
    contextRequired: null,
    response: 'GREET', setsContext: 'GREETED', tool: null,
  },
  {
    id: 'GREET_009', priority: 6,
    patterns: [/\b(long time no see|it'?s been a while|we meet again)\b/i],
    contextRequired: null,
    response: 'GREET', setsContext: 'GREETED', tool: null,
  },
  {
    id: 'GREET_010', priority: 5,
    patterns: [/^(ready|are you ready|you ready)\b/i],
    contextRequired: null,
    response: 'PRESENCE_CONFIRM', setsContext: null, tool: null,
  },

]
