// ─────────────────────────────────────────────────────────────
// MACHINE MIND — Rule Table (256 rules)
// Every rule is fully written out. No placeholders. No stubs.
// ─────────────────────────────────────────────────────────────

import type { Rule } from '../types'

export const RULES: Rule[] = [

  // ═══════════════════════════════════════════════════════════
  // EDGE CASES — priority 100
  // ═══════════════════════════════════════════════════════════
  {
    id: 'EDGE_001',
    priority: 100,
    patterns: [/^\s*$/],
    contextRequired: null,
    response: 'It looks like you sent an empty message. Could you try again?',
    setsContext: null,
    tool: null,
  },
  {
    id: 'EDGE_002',
    priority: 100,
    patterns: [/^[\s\S]{500,}$/],
    contextRequired: null,
    response: 'That\'s quite a long message! Could you summarize your question so I can help you more effectively?',
    setsContext: null,
    tool: null,
  },
  {
    id: 'EDGE_003',
    priority: 100,
    patterns: [/^[^\w\s]+$/, /^[^a-zA-Z0-9]+$/],
    contextRequired: null,
    response: 'I see special characters but no words. Could you rephrase that?',
    setsContext: null,
    tool: null,
  },
  {
    id: 'EDGE_004',
    priority: 100,
    patterns: [/^(.)\1{4,}$/, /^(\b\w+\b)\s+\1\s+\1\s+\1/],
    contextRequired: null,
    response: 'It looks like you\'re repeating yourself. Is there something specific I can help with?',
    setsContext: null,
    tool: null,
  },
  {
    id: 'EDGE_005',
    priority: 100,
    patterns: [/^[bcdfghjklmnpqrstvwxyz]{5,}$/i],
    contextRequired: null,
    response: 'That doesn\'t seem like a recognizable word. Could you try rephrasing?',
    setsContext: null,
    tool: null,
  },
  {
    id: 'EDGE_006',
    priority: 100,
    patterns: [/^\d+$/, /^\d+\s*\d+$/],
    contextRequired: null,
    response: 'You\'ve entered a number. Would you like me to do something with it? For example, I can convert it, calculate with it, or tell you about it.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'EDGE_007',
    priority: 100,
    patterns: [/^\w$/],
    contextRequired: null,
    response: 'A single character doesn\'t give me much to work with. Could you elaborate?',
    setsContext: null,
    tool: null,
  },
  {
    id: 'EDGE_008',
    priority: 100,
    patterns: [/^\w{1,3}$/],
    contextRequired: null,
    response: 'That\'s very brief! Could you provide more context so I can assist you better?',
    setsContext: null,
    tool: null,
  },
  {
    id: 'EDGE_009',
    priority: 100,
    patterns: [/^[A-Z\s!]{5,}$/],
    contextRequired: null,
    response: 'No need to shout! I can hear you just fine. How can I help?',
    setsContext: null,
    tool: null,
  },
  {
    id: 'EDGE_010',
    priority: 100,
    patterns: [/[\u4e00-\u9fff]+/, /[\u3040-\u309f]+/, /[\u0400-\u04ff]+/],
    contextRequired: null,
    response: 'I detected non-Latin script in your message. I primarily understand English. Could you rephrase in English?',
    setsContext: null,
    tool: null,
  },

  // ═══════════════════════════════════════════════════════════
  // MATH — priority 95
  // ═══════════════════════════════════════════════════════════
  {
    id: 'MATH_001',
    priority: 95,
    patterns: [/\b(?:calc(?:ulate)?|compute|solve|eval(?:uate)?)\b/i],
    contextRequired: null,
    response: 'Calculating...',
    setsContext: 'math_operation',
    tool: 'math',
  },
  {
    id: 'MATH_002',
    priority: 95,
    patterns: [/\d+\s*[+\-*/^%]\s*\d+/, /[+\-*/^%]\s*\d+/],
    contextRequired: null,
    response: 'Solving expression...',
    setsContext: 'math_operation',
    tool: 'math',
  },
  {
    id: 'MATH_003',
    priority: 95,
    patterns: [/\bsqrt\b|\bsquare\s*root\b|\bcube\s*root\b|\broots?\b.*\bof\b/i],
    contextRequired: null,
    response: 'Computing root...',
    setsContext: 'math_operation',
    tool: 'math',
  },
  {
    id: 'MATH_004',
    priority: 95,
    patterns: [/\bpercent(?:age)?\s+(?:of|increase|decrease|change)\b|\bwhat\s+(?:is\s+)?\d+\s*%\s*(?:of|off)\b/i],
    contextRequired: null,
    response: 'Computing percentage...',
    setsContext: 'math_operation',
    tool: 'math',
  },
  {
    id: 'MATH_005',
    priority: 95,
    patterns: [/\b(?:power|raised|exponent|to\s+the\s+(?:power|nth))\b/i],
    contextRequired: null,
    response: 'Computing power...',
    setsContext: 'math_operation',
    tool: 'math',
  },
  {
    id: 'MATH_006',
    priority: 95,
    patterns: [/\bfactorial\b|\b\d+!\b/i],
    contextRequired: null,
    response: 'Computing factorial...',
    setsContext: 'math_operation',
    tool: 'math',
  },
  {
    id: 'MATH_007',
    priority: 95,
    patterns: [/\b(?:sin|cos|tan|asin|acos|atan|sec|csc|cot)\b/i],
    contextRequired: null,
    response: 'Computing trigonometric function...',
    setsContext: 'math_operation',
    tool: 'math',
  },
  {
    id: 'MATH_008',
    priority: 95,
    patterns: [/\blog(?:arithm)?\b|\bln\b/i],
    contextRequired: null,
    response: 'Computing logarithm...',
    setsContext: 'math_operation',
    tool: 'math',
  },
  {
    id: 'MATH_009',
    priority: 95,
    patterns: [/\baverage\b|\bmean\b|\bmedian\b|\bmode\b/i],
    contextRequired: null,
    response: 'Computing average...',
    setsContext: 'math_operation',
    tool: 'math',
  },
  {
    id: 'MATH_010',
    priority: 95,
    patterns: [/\bmin(?:imum)?\b|\bmax(?:imum)?\b/i],
    contextRequired: null,
    response: 'Finding min/max...',
    setsContext: 'math_operation',
    tool: 'math',
  },
  {
    id: 'MATH_011',
    priority: 95,
    patterns: [/\bmod(?:ulo)?\b|\bremainder\b/i],
    contextRequired: null,
    response: 'Computing modulo...',
    setsContext: 'math_operation',
    tool: 'math',
  },
  {
    id: 'MATH_012',
    priority: 95,
    patterns: [/\babs(?:olute)?\s+(?:value|val)?\b/i],
    contextRequired: null,
    response: 'Computing absolute value...',
    setsContext: 'math_operation',
    tool: 'math',
  },

  // ═══════════════════════════════════════════════════════════
  // ENCODE — priority 92
  // ═══════════════════════════════════════════════════════════
  {
    id: 'ENC_001',
    priority: 92,
    patterns: [/\bbase\s*64\s+encode\b|\bencode\s+(?:to\s+)?base\s*64\b/i],
    contextRequired: null,
    response: 'Encoding to Base64...',
    setsContext: 'encode_base64',
    tool: 'encode',
  },
  {
    id: 'ENC_002',
    priority: 92,
    patterns: [/\bbase\s*64\s+decode\b|\bdecode\s+(?:from\s+)?base\s*64\b/i],
    contextRequired: null,
    response: 'Decoding from Base64...',
    setsContext: 'decode_base64',
    tool: 'encode',
  },
  {
    id: 'ENC_003',
    priority: 92,
    patterns: [/\burl\s+encode\b|\bencode\s+(?:url|uri)\b|\bpercent\s+encode\b/i],
    contextRequired: null,
    response: 'URL encoding...',
    setsContext: 'encode_url',
    tool: 'encode',
  },
  {
    id: 'ENC_004',
    priority: 92,
    patterns: [/\burl\s+decode\b|\bdecode\s+(?:url|uri)\b|\bpercent\s+decode\b/i],
    contextRequired: null,
    response: 'URL decoding...',
    setsContext: 'decode_url',
    tool: 'encode',
  },
  {
    id: 'ENC_005',
    priority: 92,
    patterns: [/\bhex\s+encode\b|\bencode\s+hex\b|\bto\s+hex(?:adecimal)?\b/i],
    contextRequired: null,
    response: 'Encoding to hex...',
    setsContext: 'encode_hex',
    tool: 'encode',
  },
  {
    id: 'ENC_006',
    priority: 92,
    patterns: [/\bmorse\b/i],
    contextRequired: null,
    response: 'Converting Morse code...',
    setsContext: 'encode_morse',
    tool: 'encode',
  },
  {
    id: 'ENC_007',
    priority: 92,
    patterns: [/\brot\s*13\b/i],
    contextRequired: null,
    response: 'Applying ROT13...',
    setsContext: 'encode_rot13',
    tool: 'encode',
  },
  {
    id: 'ENC_008',
    priority: 92,
    patterns: [/\bbinary\s+encode\b|\bencode\s+binary\b|\bto\s+binary\b/i],
    contextRequired: null,
    response: 'Encoding to binary...',
    setsContext: 'encode_binary',
    tool: 'encode',
  },

  // ═══════════════════════════════════════════════════════════
  // HASH — priority 91
  // ═══════════════════════════════════════════════════════════
  {
    id: 'HASH_001',
    priority: 91,
    patterns: [/\bsha\s*?256\b|\bsha256\s+hash\b/i],
    contextRequired: null,
    response: 'Generating SHA-256 hash...',
    setsContext: 'hash_sha256',
    tool: 'hash',
  },
  {
    id: 'HASH_002',
    priority: 91,
    patterns: [/\bmd5\b/i],
    contextRequired: null,
    response: 'Generating MD5 hash...',
    setsContext: 'hash_md5',
    tool: 'hash',
  },
  {
    id: 'HASH_003',
    priority: 91,
    patterns: [/\buuid\b|\bgenerate\s+uuid\b|\bguid\b/i],
    contextRequired: null,
    response: 'Generating UUID...',
    setsContext: 'hash_uuid',
    tool: 'hash',
  },
  {
    id: 'HASH_004',
    priority: 91,
    patterns: [/\bsha\s*?1\b|\bsha1\s+hash\b/i],
    contextRequired: null,
    response: 'Generating SHA-1 hash...',
    setsContext: 'hash_sha1',
    tool: 'hash',
  },
  {
    id: 'HASH_005',
    priority: 91,
    patterns: [/\bsha\s*?512\b|\bsha512\s+hash\b/i],
    contextRequired: null,
    response: 'Generating SHA-512 hash...',
    setsContext: 'hash_sha512',
    tool: 'hash',
  },
  {
    id: 'HASH_006',
    priority: 91,
    patterns: [/\bhash\b(?:\s+(?:this|the|text|string))?/i],
    contextRequired: null,
    response: 'Hashing text...',
    setsContext: 'hash_general',
    tool: 'hash',
  },

  // ═══════════════════════════════════════════════════════════
  // COLOR — priority 90
  // ═══════════════════════════════════════════════════════════
  {
    id: 'COLR_001',
    priority: 90,
    patterns: [/\bhex\s+(?:to\s+)?rgb\b|\brgb\s+from\s+hex\b|#[0-9a-fA-F]{3,8}(?:\b|$|\s)/],
    contextRequired: null,
    response: 'Converting color...',
    setsContext: 'color_hex',
    tool: 'color',
  },
  {
    id: 'COLR_002',
    priority: 90,
    patterns: [/\brgb\s+(?:to\s+)?hex\b|\bhex\s+from\s+rgb\b/i],
    contextRequired: null,
    response: 'Converting RGB to hex...',
    setsContext: 'color_rgb',
    tool: 'color',
  },
  {
    id: 'COLR_003',
    priority: 90,
    patterns: [/\bcolor\s+info(?:rmation)?\b|\binfo\s+(?:on|about)\s+(?:the\s+)?color\b/i],
    contextRequired: null,
    response: 'Looking up color information...',
    setsContext: 'color_info',
    tool: 'color',
  },
  {
    id: 'COLR_004',
    priority: 90,
    patterns: [/\bhsl\b.*\b(?:convert|to)\b|\bconvert.*\bhsl\b/i],
    contextRequired: null,
    response: 'Converting HSL color...',
    setsContext: 'color_hsl',
    tool: 'color',
  },
  {
    id: 'COLR_005',
    priority: 90,
    patterns: [/\bcontrast\s+(?:check|ratio|between)\b/i],
    contextRequired: null,
    response: 'Checking color contrast...',
    setsContext: 'color_contrast',
    tool: 'color',
  },
  {
    id: 'COLR_006',
    priority: 90,
    patterns: [/\bpalette\b|\bcolor\s+palette\b|\bscheme\b/i],
    contextRequired: null,
    response: 'Generating color palette...',
    setsContext: 'color_palette',
    tool: 'color',
  },
  {
    id: 'COLR_007',
    priority: 90,
    patterns: [/\bcomplement(?:ary)?\s+color\b/i],
    contextRequired: null,
    response: 'Finding complementary color...',
    setsContext: 'color_complement',
    tool: 'color',
  },
  {
    id: 'COLR_008',
    priority: 90,
    patterns: [/\brandom\s+color\b/i],
    contextRequired: null,
    response: 'Generating random color...',
    setsContext: 'color_random',
    tool: 'color',
  },

  // ═══════════════════════════════════════════════════════════
  // REGEX — priority 89
  // ═══════════════════════════════════════════════════════════
  {
    id: 'REGX_001',
    priority: 89,
    patterns: [/\btest\s+regex\b|\bregex\s+test\b|\bmatch\s+pattern\b/i],
    contextRequired: null,
    response: 'Testing regex pattern...',
    setsContext: 'regex_test',
    tool: 'regex',
  },
  {
    id: 'REGX_002',
    priority: 89,
    patterns: [/\bexplain\s+regex\b|\bregex\s+explain\b|\bwhat\s+does\s+(?:this\s+)?regex\s+(?:do|mean)\b/i],
    contextRequired: null,
    response: 'Explaining regex pattern...',
    setsContext: 'regex_explain',
    tool: 'regex',
  },
  {
    id: 'REGX_003',
    priority: 89,
    patterns: [/\bemail\s+regex\b|\bregex\s+(?:for|to\s+match)\s+email\b/i],
    contextRequired: null,
    response: 'Here\'s a common email regex pattern...',
    setsContext: 'regex_email',
    tool: 'regex',
  },
  {
    id: 'REGX_004',
    priority: 89,
    patterns: [/\bphone\s+regex\b|\bregex\s+(?:for|to\s+match)\s+phone\b/i],
    contextRequired: null,
    response: 'Here\'s a common phone number regex pattern...',
    setsContext: 'regex_phone',
    tool: 'regex',
  },
  {
    id: 'REGX_005',
    priority: 89,
    patterns: [/\burl\s+regex\b|\bregex\s+(?:for|to\s+match)\s+(?:url|link)\b/i],
    contextRequired: null,
    response: 'Here\'s a common URL regex pattern...',
    setsContext: 'regex_url',
    tool: 'regex',
  },
  {
    id: 'REGX_006',
    priority: 89,
    patterns: [/\bcommon\s+regex\b|\bregex\s+cheat\s*sheet\b|\bregex\s+pattern\b/i],
    contextRequired: null,
    response: 'Here are common regex patterns...',
    setsContext: 'regex_common',
    tool: 'regex',
  },

  // ═══════════════════════════════════════════════════════════
  // TIME — priority 88
  // ═══════════════════════════════════════════════════════════
  {
    id: 'TIME_001',
    priority: 88,
    patterns: [/\bwhat\s+time\b|\bcurrent\s+time\b|\btime\s+(?:is\s+)?(?:it|now)\b/i],
    contextRequired: null,
    response: 'Getting current time...',
    setsContext: 'time_query',
    tool: 'time',
  },
  {
    id: 'TIME_002',
    priority: 88,
    patterns: [/\bwhat(?:\'s|\s+is)\s+(?:the\s+)?date\b|\bcurrent\s+date\b|\btoday(?:\'s|\s+)date\b/i],
    contextRequired: null,
    response: 'Getting current date...',
    setsContext: 'date_query',
    tool: 'time',
  },
  {
    id: 'TIME_003',
    priority: 88,
    patterns: [/\bwhat\s+day\b|\bday\s+(?:is\s+)?(?:it|today)\b/i],
    contextRequired: null,
    response: 'Getting current day...',
    setsContext: 'day_query',
    tool: 'time',
  },
  {
    id: 'TIME_004',
    priority: 88,
    patterns: [/\btime\s+(?:in|at|for)\s+\w+|\bwhat\s+time\s+(?:is\s+it\s+)?(?:in|at)\b/i],
    contextRequired: null,
    response: 'Getting timezone time...',
    setsContext: 'timezone_query',
    tool: 'time',
  },
  {
    id: 'TIME_005',
    priority: 88,
    patterns: [/\bhow\s+many\s+(?:days?|hours?|minutes?)\s+(?:until|till|before|to)\b/i],
    contextRequired: null,
    response: 'Calculating time until...',
    setsContext: 'countdown_query',
    tool: 'time',
  },
  {
    id: 'TIME_006',
    priority: 88,
    patterns: [/\bdate\s+(?:and\s+)?time\b|\btime\s+(?:and\s+)?date\b/i],
    contextRequired: null,
    response: 'Getting date and time...',
    setsContext: 'datetime_query',
    tool: 'time',
  },
  {
    id: 'TIME_007',
    priority: 88,
    patterns: [/\bcountdown\b/i],
    contextRequired: null,
    response: 'Starting countdown...',
    setsContext: 'countdown_query',
    tool: 'time',
  },
  {
    id: 'TIME_008',
    priority: 88,
    patterns: [/\bunix\s+timestamp\b|\bepoch\s+time\b|\bposix\s+time\b/i],
    contextRequired: null,
    response: 'Getting Unix timestamp...',
    setsContext: 'unix_query',
    tool: 'time',
  },
  {
    id: 'TIME_009',
    priority: 88,
    patterns: [/\btimezone\b|\btime\s+zone\b/i],
    contextRequired: null,
    response: 'Getting timezone info...',
    setsContext: 'timezone_query',
    tool: 'time',
  },
  {
    id: 'TIME_010',
    priority: 88,
    patterns: [/\bleap\s+year\b/i],
    contextRequired: null,
    response: 'Checking leap year...',
    setsContext: 'leap_year_query',
    tool: 'time',
  },

  // ═══════════════════════════════════════════════════════════
  // CONVERT — priority 87
  // ═══════════════════════════════════════════════════════════
  {
    id: 'CONV_001',
    priority: 87,
    patterns: [/\b(?:celsius|fahrenheit|kelvin)\s+to\s+(?:celsius|fahrenheit|kelvin)\b|\bconvert\s+.*(?:celsius|fahrenheit|kelvin)\b|\b°[cCfFkK]\b/i],
    contextRequired: null,
    response: 'Converting temperature...',
    setsContext: 'convert_temp',
    tool: 'convert',
  },
  {
    id: 'CONV_002',
    priority: 87,
    patterns: [/\b(?:km|mi|miles?|kilometers?|meters?|feet|ft|inches?|cm|mm|yd|yards?)\s+to\s+(?:km|mi|miles?|kilometers?|meters?|feet|ft|inches?|cm|mm|yd|yards?)\b|\d+\.?\d*\s*(?:km|mi|miles?|kilometers?|meters?|feet|ft|inches?|cm|mm|yd|yards?)\s+to\s+/i],
    contextRequired: null,
    response: 'Converting length/distance...',
    setsContext: 'convert_length',
    tool: 'convert',
  },
  {
    id: 'CONV_003',
    priority: 87,
    patterns: [/\b(?:kg|lbs?|pounds?|kilograms?|grams?|g|ounces?|oz|tons?)\s+to\s+(?:kg|lbs?|pounds?|kilograms?|grams?|g|ounces?|oz|tons?)\b/i],
    contextRequired: null,
    response: 'Converting weight/mass...',
    setsContext: 'convert_weight',
    tool: 'convert',
  },
  {
    id: 'CONV_004',
    priority: 87,
    patterns: [/\b(?:mph|kph|km\/h|m\/s|ft\/s|knots?)\s+to\s+(?:mph|kph|km\/h|m\/s|ft\/s|knots?)\b/i],
    contextRequired: null,
    response: 'Converting speed...',
    setsContext: 'convert_speed',
    tool: 'convert',
  },
  {
    id: 'CONV_005',
    priority: 87,
    patterns: [/\b(?:bytes?|kb|mb|gb|tb|pb)\s+to\s+(?:bytes?|kb|mb|gb|tb|pb)\b/i],
    contextRequired: null,
    response: 'Converting data size...',
    setsContext: 'convert_data',
    tool: 'convert',
  },
  {
    id: 'CONV_006',
    priority: 87,
    patterns: [/\b(?:sq\s*(?:ft|m|yd|mi|km)|acres?|hectares?|sq\s*in)\s+to\s/i],
    contextRequired: null,
    response: 'Converting area...',
    setsContext: 'convert_area',
    tool: 'convert',
  },
  {
    id: 'CONV_007',
    priority: 87,
    patterns: [/\b(?:liters?|l|gallons?|gal|ml|cups?|pints?|quarts?|fl\s*oz)\s+to\s/i],
    contextRequired: null,
    response: 'Converting volume...',
    setsContext: 'convert_volume',
    tool: 'convert',
  },
  {
    id: 'CONV_008',
    priority: 87,
    patterns: [/\b(?:seconds?|minutes?|hours?|days?|weeks?|months?|years?)\s+to\s+(?:seconds?|minutes?|hours?|days?|weeks?|months?|years?)\b/i],
    contextRequired: null,
    response: 'Converting time units...',
    setsContext: 'convert_time',
    tool: 'convert',
  },
  {
    id: 'CONV_009',
    priority: 87,
    patterns: [/\b(?:degrees?|radians?|gradians?)\s+to\s+(?:degrees?|radians?|gradians?)\b/i],
    contextRequired: null,
    response: 'Converting angle units...',
    setsContext: 'convert_angle',
    tool: 'convert',
  },
  {
    id: 'CONV_010',
    priority: 87,
    patterns: [/\bconvert\b/i],
    contextRequired: null,
    response: 'Converting...',
    setsContext: 'convert_general',
    tool: 'convert',
  },

  // ═══════════════════════════════════════════════════════════
  // RANDOM — priority 86
  // ═══════════════════════════════════════════════════════════
  {
    id: 'RAND_001',
    priority: 86,
    patterns: [/\broll\s+(?:a\s+)?(?:dice|die|d\d+)\b|\b(?:dice|die)\s+roll\b|\d+d\d+|\b!roll\b|\b!random\b|\b!rand\b|\b!dice\b/i],
    contextRequired: null,
    response: 'Rolling dice...',
    setsContext: 'random_dice',
    tool: 'random',
  },
  {
    id: 'RAND_002',
    priority: 86,
    patterns: [/\bflip\s+(?:a\s+)?coin\b|\bcoin\s+flip\b|\bheads\s+or\s+tails\b/i],
    contextRequired: null,
    response: 'Flipping coin...',
    setsContext: 'random_coin',
    tool: 'random',
  },
  {
    id: 'RAND_003',
    priority: 86,
    patterns: [/\brandom\s+number\b|\bgenerate\s+(?:a\s+)?random\s+number\b/i],
    contextRequired: null,
    response: 'Generating random number...',
    setsContext: 'random_number',
    tool: 'random',
  },
  {
    id: 'RAND_004',
    priority: 86,
    patterns: [/\brandom\s+password\b|\bgenerate\s+(?:a\s+)?password\b/i],
    contextRequired: null,
    response: 'Generating random password...',
    setsContext: 'random_password',
    tool: 'random',
  },
  {
    id: 'RAND_005',
    priority: 86,
    patterns: [/\bpick\s+(?:from|one|a|random)\b|\bchoose\s+(?:from|one|a|random)\b/i],
    contextRequired: null,
    response: 'Picking random choice...',
    setsContext: 'random_pick',
    tool: 'random',
  },
  {
    id: 'RAND_006',
    priority: 86,
    patterns: [/\bshuffle\b/i],
    contextRequired: null,
    response: 'Shuffling...',
    setsContext: 'random_shuffle',
    tool: 'random',
  },
  {
    id: 'RAND_007',
    priority: 86,
    patterns: [/\brandom\s+color\b/i],
    contextRequired: null,
    response: 'Generating random color...',
    setsContext: 'random_color',
    tool: 'random',
  },
  {
    id: 'RAND_008',
    priority: 86,
    patterns: [/\brandom\s+uuid\b|\bgenerate\s+uuid\b/i],
    contextRequired: null,
    response: 'Generating random UUID...',
    setsContext: 'random_uuid',
    tool: 'random',
  },
  {
    id: 'RAND_009',
    priority: 86,
    patterns: [/\brandom\s+letter\b|\brandom\s+char(?:acter)?\b/i],
    contextRequired: null,
    response: 'Generating random letter...',
    setsContext: 'random_letter',
    tool: 'random',
  },
  {
    id: 'RAND_010',
    priority: 86,
    patterns: [/\byes\s+or\s+no\b|\byes\/no\b/i],
    contextRequired: null,
    response: 'Choosing yes or no...',
    setsContext: 'random_yesno',
    tool: 'random',
  },

  // ═══════════════════════════════════════════════════════════
  // MEMORY — priority 85
  // ═══════════════════════════════════════════════════════════
  {
    id: 'MEM_001',
    priority: 85,
    patterns: [/\bremember\s+(?:that\s+)?/i, /\bstore\s+(?:that\s+)?/i, /\bsave\s+(?:that\s+)?/i],
    contextRequired: null,
    response: 'I\'ll remember that for you.',
    setsContext: 'memory_stored',
    tool: 'memory',
  },
  {
    id: 'MEM_002',
    priority: 85,
    patterns: [/\brecall\b|\bwhat\s+did\s+i\s+(?:tell|say|ask)\b|\bwhat\s+(?:do\s+you|did\s+you)\s+(?:know|remember)\b/i],
    contextRequired: null,
    response: 'Let me check my memory...',
    setsContext: 'memory_recall',
    tool: 'memory',
  },
  {
    id: 'MEM_003',
    priority: 85,
    patterns: [/\bforget\b|\bdelete\s+(?:that|memory|note)\b|\berase\b/i],
    contextRequired: null,
    response: 'Forgetting that item...',
    setsContext: 'memory_forgotten',
    tool: 'memory',
  },
  {
    id: 'MEM_004',
    priority: 85,
    patterns: [/\blist\s+(?:all\s+)?(?:memories|notes|stored)\b|\bshow\s+(?:me\s+)?(?:my\s+)?(?:memories|notes)\b/i],
    contextRequired: null,
    response: 'Listing stored memories...',
    setsContext: 'memory_list',
    tool: 'memory',
  },
  {
    id: 'MEM_005',
    priority: 85,
    patterns: [/\bsave\s+(?:a\s+)?note\b|\bnote\s+(?:that|down)\b/i],
    contextRequired: null,
    response: 'Saving note...',
    setsContext: 'memory_stored',
    tool: 'memory',
  },
  {
    id: 'MEM_006',
    priority: 85,
    patterns: [/\bwhat\s+did\s+i\s+tell\s+you\s+about\b/i],
    contextRequired: null,
    response: 'Checking what you told me...',
    setsContext: 'memory_recall',
    tool: 'memory',
  },
  {
    id: 'MEM_007',
    priority: 85,
    patterns: [/\bwhat\s+do\s+you\s+know\s+about\s+me\b/i],
    contextRequired: null,
    response: 'Let me check what I know about you...',
    setsContext: 'memory_recall',
    tool: 'memory',
  },
  {
    id: 'MEM_008',
    priority: 85,
    patterns: [/\bclear\s+(?:all\s+)?(?:memories|notes|memory)\b|\bwipe\s+(?:your\s+)?memory\b/i],
    contextRequired: null,
    response: 'Clearing all memories...',
    setsContext: 'memory_cleared',
    tool: 'memory',
  },
  {
    id: 'MEM_009',
    priority: 85,
    patterns: [/\bupdate\s+(?:the\s+)?(?:memory|note)\b/i],
    contextRequired: null,
    response: 'Updating memory...',
    setsContext: 'memory_updated',
    tool: 'memory',
  },
  {
    id: 'MEM_010',
    priority: 85,
    patterns: [/\bhow\s+many\s+(?:memories|notes|things)\s+do\s+you\s+(?:remember|have\s+stored)\b/i],
    contextRequired: null,
    response: 'Counting stored memories...',
    setsContext: 'memory_count',
    tool: 'memory',
  },

  // ═══════════════════════════════════════════════════════════
  // WORD — priority 84
  // ═══════════════════════════════════════════════════════════
  {
    id: 'WORD_001',
    priority: 84,
    patterns: [/\bword\s+count\b|\bcount\s+(?:the\s+)?words?\b|\bhow\s+many\s+words\b/i],
    contextRequired: null,
    response: 'Counting words...',
    setsContext: 'word_count',
    tool: 'word',
  },
  {
    id: 'WORD_002',
    priority: 84,
    patterns: [/\bchar(?:acter)?\s+count\b|\bcount\s+(?:the\s+)?char(?:acters)?\b|\bhow\s+many\s+char(?:acters)?\b/i],
    contextRequired: null,
    response: 'Counting characters...',
    setsContext: 'char_count',
    tool: 'word',
  },
  {
    id: 'WORD_003',
    priority: 84,
    patterns: [/\bpalindrome\b/i],
    contextRequired: null,
    response: 'Checking palindrome...',
    setsContext: 'word_palindrome',
    tool: 'word',
  },
  {
    id: 'WORD_004',
    priority: 84,
    patterns: [/\banagram\b/i],
    contextRequired: null,
    response: 'Checking anagram...',
    setsContext: 'word_anagram',
    tool: 'word',
  },
  {
    id: 'WORD_005',
    priority: 84,
    patterns: [/\breverse\s+(?:the\s+)?(?:text|string|word|sentence)\b/i],
    contextRequired: null,
    response: 'Reversing text...',
    setsContext: 'word_reverse',
    tool: 'word',
  },
  {
    id: 'WORD_006',
    priority: 84,
    patterns: [/\breadability\b|\breadability\s+score\b|\breading\s+level\b/i],
    contextRequired: null,
    response: 'Computing readability score...',
    setsContext: 'word_readability',
    tool: 'word',
  },
  {
    id: 'WORD_007',
    priority: 84,
    patterns: [/\bspell\s+out\s+(?:the\s+)?number\b|\bnumber\s+to\s+words?\b/i],
    contextRequired: null,
    response: 'Spelling out number...',
    setsContext: 'word_spellout',
    tool: 'word',
  },
  {
    id: 'WORD_008',
    priority: 84,
    patterns: [/\btitle\s+case\b|\bcapitalize\b/i],
    contextRequired: null,
    response: 'Converting to title case...',
    setsContext: 'word_titlecase',
    tool: 'word',
  },
  {
    id: 'WORD_009',
    priority: 84,
    patterns: [/\bword\s+frequency\b|\bfrequency\s+(?:of|count)\b/i],
    contextRequired: null,
    response: 'Computing word frequency...',
    setsContext: 'word_frequency',
    tool: 'word',
  },
  {
    id: 'WORD_010',
    priority: 84,
    patterns: [/\bsyllable\s+count\b|\bcount\s+syllables?\b/i],
    contextRequired: null,
    response: 'Counting syllables...',
    setsContext: 'word_syllable',
    tool: 'word',
  },

  // ═══════════════════════════════════════════════════════════
  // JSON — priority 83
  // ═══════════════════════════════════════════════════════════
  {
    id: 'JSON_001',
    priority: 83,
    patterns: [/\bparse\s+json\b|\bjson\s+parse\b/i],
    contextRequired: null,
    response: 'Parsing JSON...',
    setsContext: 'json_parse',
    tool: 'json',
  },
  {
    id: 'JSON_002',
    priority: 83,
    patterns: [/\bvalidate\s+json\b|\bjson\s+valid(?:ate|ation|ity)\b|\bis\s+(?:this\s+)?(?:valid\s+)?json\b/i],
    contextRequired: null,
    response: 'Validating JSON...',
    setsContext: 'json_validate',
    tool: 'json',
  },
  {
    id: 'JSON_003',
    priority: 83,
    patterns: [/\bformat\s+json\b|\bbeautif(?:y|y)\s+json\b|\bpretty\s+print\s+json\b|\bjson\s+format\b/i],
    contextRequired: null,
    response: 'Formatting JSON...',
    setsContext: 'json_format',
    tool: 'json',
  },
  {
    id: 'JSON_004',
    priority: 83,
    patterns: [/\bextract\s+(?:json\s+)?path\b|\bjson\s+path\b|\bjsonpath\b|\bget\s+(?:value\s+)?from\s+json\b/i],
    contextRequired: null,
    response: 'Extracting JSON path...',
    setsContext: 'json_path',
    tool: 'json',
  },
  {
    id: 'JSON_005',
    priority: 83,
    patterns: [/\bminify\s+json\b|\bjson\s+minify\b|\bcompact\s+json\b/i],
    contextRequired: null,
    response: 'Minifying JSON...',
    setsContext: 'json_minify',
    tool: 'json',
  },
  {
    id: 'JSON_006',
    priority: 83,
    patterns: [/\bjson\s+to\s+csv\b|\bcsv\s+from\s+json\b/i],
    contextRequired: null,
    response: 'Converting JSON to CSV...',
    setsContext: 'json_to_csv',
    tool: 'json',
  },

  // ═══════════════════════════════════════════════════════════
  // SYSTEM — priority 80
  // ═══════════════════════════════════════════════════════════
  {
    id: 'SYS_001',
    priority: 80,
    patterns: [/\bhelp\b|\b!help\b|\b!tools\b|\b!status\b/i],
    contextRequired: null,
    response: 'Here\'s what I can help with:\n• Math: calculate, solve expressions\n• Time: current time, date, timezone\n• Convert: units, temperature, length\n• Encode: base64, hex, URL, morse, ROT13\n• Hash: SHA-256, MD5, UUID\n• Color: hex/RGB, palette, contrast\n• Regex: test, explain patterns\n• Random: dice, coin, password\n• Memory: store, recall, list\n• Word: count, palindrome, readability\n• JSON: parse, validate, format\nType any command or question to get started!',
    setsContext: 'help_shown',
    tool: null,
  },
  {
    id: 'SYS_002',
    priority: 80,
    patterns: [/\bstatus\b|\bsystem\s+status\b/i],
    contextRequired: null,
    response: 'Checking system status...',
    setsContext: null,
    tool: 'system_status',
  },
  {
    id: 'SYS_003',
    priority: 80,
    patterns: [/\b(?:list|show)\s+(?:all\s+)?(?:tools?|commands?|capabilities)\b/i],
    contextRequired: null,
    response: 'Listing available tools...',
    setsContext: 'tools_listed',
    tool: 'system_status',
  },
  {
    id: 'SYS_004',
    priority: 80,
    patterns: [/\bswitch\s+(?:to\s+)?mode\b|\b(?:ai|rule)\s+mode\b/i],
    contextRequired: null,
    response: 'Switching mode...',
    setsContext: 'mode_switch',
    tool: 'system_status',
  },
  {
    id: 'SYS_005',
    priority: 80,
    patterns: [/\bclear\s+(?:chat|conversation|history|session)\b|\breset\s+(?:chat|conversation)?\b|\bstart\s+over\b/i],
    contextRequired: null,
    response: 'Clearing conversation...',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SYS_006',
    priority: 80,
    patterns: [/\bversion\b/i],
    contextRequired: null,
    response: 'MACHINE MIND v1.0.0 — Rule Engine + AI Relay',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SYS_007',
    priority: 80,
    patterns: [/\babout\b/i],
    contextRequired: null,
    response: 'MACHINE MIND is an intelligent chat interface with a built-in rule engine and AI relay. It can perform calculations, conversions, encoding, and much more!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SYS_008',
    priority: 80,
    patterns: [/\bdebug\b/i],
    contextRequired: null,
    response: 'Debug mode info...',
    setsContext: 'debug_mode',
    tool: 'system_status',
  },

  // ═══════════════════════════════════════════════════════════
  // CHAIN — priority 78
  // ═══════════════════════════════════════════════════════════
  {
    id: 'CHAIN_001',
    priority: 78,
    patterns: [/\bpipe\b|\bchain\b|\bthen\b.*\b(?:also|and|then)\b/i],
    contextRequired: null,
    response: 'Chaining operations...',
    setsContext: 'chain_active',
    tool: 'chain',
  },
  {
    id: 'CHAIN_002',
    priority: 78,
    patterns: [/\bthen\b/i],
    contextRequired: 'tool_result',
    response: 'Continuing chain...',
    setsContext: 'chain_active',
    tool: 'chain',
  },
  {
    id: 'CHAIN_003',
    priority: 78,
    patterns: [/\band\s+also\b|\bthen\s+also\b/i],
    contextRequired: 'tool_result',
    response: 'Adding to chain...',
    setsContext: 'chain_active',
    tool: 'chain',
  },
  {
    id: 'CHAIN_004',
    priority: 78,
    patterns: [/\bdo\s+multiple\s+things\b|\bstep\s+by\s+step\b/i],
    contextRequired: null,
    response: 'Setting up multi-step operation...',
    setsContext: 'chain_active',
    tool: 'chain',
  },

  // ═══════════════════════════════════════════════════════════
  // GREETING — priority 75
  // ═══════════════════════════════════════════════════════════
  {
    id: 'GREET_001',
    priority: 75,
    patterns: [/\bhello\b/i],
    contextRequired: null,
    response: 'Hello! How can I help you today?',
    setsContext: 'greeted',
    tool: null,
  },
  {
    id: 'GREET_002',
    priority: 75,
    patterns: [/\bhi\b/i],
    contextRequired: null,
    response: 'Hi there! What can I do for you?',
    setsContext: 'greeted',
    tool: null,
  },
  {
    id: 'GREET_003',
    priority: 75,
    patterns: [/\bhey\b/i],
    contextRequired: null,
    response: 'Hey! What\'s on your mind?',
    setsContext: 'greeted',
    tool: null,
  },
  {
    id: 'GREET_004',
    priority: 75,
    patterns: [/\bgood\s+(?:morning|afternoon|evening|day)\b/i],
    contextRequired: null,
    response: 'Good day to you too! How can I assist?',
    setsContext: 'greeted',
    tool: null,
  },
  {
    id: 'GREET_005',
    priority: 75,
    patterns: [/\bsup\b|\bwhat'?s\s+up\b|\bhowdy\b/i],
    contextRequired: null,
    response: 'Hey! Not much, just here to help. What do you need?',
    setsContext: 'greeted',
    tool: null,
  },
  {
    id: 'GREET_006',
    priority: 75,
    patterns: [/\bgreetings\b|\bsalutations\b/i],
    contextRequired: null,
    response: 'Greetings! I\'m at your service. How may I assist you?',
    setsContext: 'greeted',
    tool: null,
  },
  {
    id: 'GREET_007',
    priority: 75,
    patterns: [/\bhola\b|\bbonjour\b|\bciao\b|\bnamaste\b|\bhallo\b/i],
    contextRequired: null,
    response: 'Hello in any language! How can I help you today?',
    setsContext: 'greeted',
    tool: null,
  },
  {
    id: 'GREET_008',
    priority: 75,
    patterns: [/\bwelcome\s+back\b|\bwelcome\b/i],
    contextRequired: null,
    response: 'Welcome back! Good to see you again. What can I help with?',
    setsContext: 'greeted',
    tool: null,
  },
  {
    id: 'GREET_009',
    priority: 75,
    patterns: [/\bhey\s+there\b|\bhi\s+there\b/i],
    contextRequired: null,
    response: 'Hey there! What can I do for you?',
    setsContext: 'greeted',
    tool: null,
  },
  {
    id: 'GREET_010',
    priority: 75,
    patterns: [/\bhiya\b/i],
    contextRequired: null,
    response: 'Hiya! Ready to help. What do you need?',
    setsContext: 'greeted',
    tool: null,
  },
  {
    id: 'GREET_011',
    priority: 75,
    patterns: [/\baloha\b/i],
    contextRequired: null,
    response: 'Aloha! How can I assist you today?',
    setsContext: 'greeted',
    tool: null,
  },
  {
    id: 'GREET_012',
    priority: 75,
    patterns: [/\byo\b/i],
    contextRequired: null,
    response: 'Yo! What\'s happening?',
    setsContext: 'greeted',
    tool: null,
  },

  // ═══════════════════════════════════════════════════════════
  // FAREWELL — priority 75
  // ═══════════════════════════════════════════════════════════
  {
    id: 'FARE_001',
    priority: 75,
    patterns: [/\bgood\s*bye\b|\bbye\b/i],
    contextRequired: null,
    response: 'Goodbye! Have a great day!',
    setsContext: 'farewell',
    tool: null,
  },
  {
    id: 'FARE_002',
    priority: 75,
    patterns: [/\bsee\s+you\b|\bsee\s+ya\b|\bsee\s+u\b/i],
    contextRequired: null,
    response: 'See you later! Come back anytime.',
    setsContext: 'farewell',
    tool: null,
  },
  {
    id: 'FARE_003',
    priority: 75,
    patterns: [/\bgood\s+night\b|\bgn\b|\bnighty?\s*night\b/i],
    contextRequired: null,
    response: 'Good night! Sleep well!',
    setsContext: 'farewell',
    tool: null,
  },
  {
    id: 'FARE_004',
    priority: 75,
    patterns: [/\btake\s+care\b/i],
    contextRequired: null,
    response: 'Take care! It was nice chatting with you.',
    setsContext: 'farewell',
    tool: null,
  },
  {
    id: 'FARE_005',
    priority: 75,
    patterns: [/\bcatch\s+(?:you|ya)\s+later\b|\bcya\b/i],
    contextRequired: null,
    response: 'Catch you later! Stay awesome!',
    setsContext: 'farewell',
    tool: null,
  },
  {
    id: 'FARE_006',
    priority: 75,
    patterns: [/\bfarewell\b/i],
    contextRequired: null,
    response: 'Farewell! Until we meet again.',
    setsContext: 'farewell',
    tool: null,
  },
  {
    id: 'FARE_007',
    priority: 75,
    patterns: [/\bsigning\s+off\b|\blogging\s+off\b|\blog\s+off\b/i],
    contextRequired: null,
    response: 'Signing off! Have a wonderful day.',
    setsContext: 'farewell',
    tool: null,
  },
  {
    id: 'FARE_008',
    priority: 75,
    patterns: [/\bgotta\s+go\b|\bgot\s+to\s+go\b|\bi\s+(?:should|must|have\s+to)\s+go\b/i],
    contextRequired: null,
    response: 'No problem, gotta go! See you next time.',
    setsContext: 'farewell',
    tool: null,
  },
  {
    id: 'FARE_009',
    priority: 75,
    patterns: [/\btalk\s+to\s+you\s+later\b|\bttul\b|\bttl\b/i],
    contextRequired: null,
    response: 'Talk to you later! Don\'t be a stranger.',
    setsContext: 'farewell',
    tool: null,
  },
  {
    id: 'FARE_010',
    priority: 75,
    patterns: [/\bpeace\s+out\b|\bpeace\b/i],
    contextRequired: null,
    response: 'Peace out! Stay safe!',
    setsContext: 'farewell',
    tool: null,
  },
  {
    id: 'FARE_011',
    priority: 75,
    patterns: [/\buntil\s+(?:next\s+time|we\s+meet\s+again|later)\b/i],
    contextRequired: null,
    response: 'Until next time! It was great talking with you.',
    setsContext: 'farewell',
    tool: null,
  },
  {
    id: 'FARE_012',
    priority: 75,
    patterns: [/\badios\b|\bciao\b|\bau\s+revoir\b|\bsayonara\b|\btschüss\b/i],
    contextRequired: null,
    response: 'Goodbye in any language! Come back soon!',
    setsContext: 'farewell',
    tool: null,
  },

  // ═══════════════════════════════════════════════════════════
  // GRATITUDE — priority 74
  // ═══════════════════════════════════════════════════════════
  {
    id: 'GRAT_001',
    priority: 74,
    patterns: [/\bthank\s+you\b|\bthanks\b/i],
    contextRequired: null,
    response: 'You\'re welcome! Happy to help.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'GRAT_002',
    priority: 74,
    patterns: [/\bthanks?\s+(?:a\s+)?lot\b|\bthanks?\s+(?:so\s+)?much\b|\bmany\s+thanks\b/i],
    contextRequired: null,
    response: 'You\'re very welcome! Always glad to assist.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'GRAT_003',
    priority: 74,
    patterns: [/\bappreciate\s+(?:it|that|your|the)\b/i],
    contextRequired: null,
    response: 'I appreciate your appreciation! Let me know if you need anything else.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'GRAT_004',
    priority: 74,
    patterns: [/\byou'?re?\s+(?:the\s+)?best\b|\byou'?re?\s+awesome\b|\byou'?re?\s+great\b/i],
    contextRequired: null,
    response: 'Thank you! That really means a lot. I try my best!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'GRAT_005',
    priority: 74,
    patterns: [/\bmuch\s+obliged\b|\bmuch\s+appreciated\b/i],
    contextRequired: null,
    response: 'The pleasure is mine! Feel free to ask anytime.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'GRAT_006',
    priority: 74,
    patterns: [/\bgrateful\b|\bgratitude\b/i],
    contextRequired: null,
    response: 'I\'m grateful for the kind words! Here to help anytime.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'GRAT_007',
    priority: 74,
    patterns: [/\bcheers\b/i],
    contextRequired: null,
    response: 'Cheers! Always happy to help.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'GRAT_008',
    priority: 74,
    patterns: [/\bty\b|\bthx\b/i],
    contextRequired: null,
    response: 'No problem! Let me know if you need anything else.',
    setsContext: null,
    tool: null,
  },

  // ═══════════════════════════════════════════════════════════
  // APOLOGY — priority 74
  // ═══════════════════════════════════════════════════════════
  {
    id: 'APOL_001',
    priority: 74,
    patterns: [/\bsorry\b/i],
    contextRequired: null,
    response: 'No worries at all! No apology needed.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'APOL_002',
    priority: 74,
    patterns: [/\bmy\s+bad\b/i],
    contextRequired: null,
    response: 'No problem! We all make mistakes. How can I help?',
    setsContext: null,
    tool: null,
  },
  {
    id: 'APOL_003',
    priority: 74,
    patterns: [/\boops\b|\bwhoops\b|\buh\s+oh\b/i],
    contextRequired: null,
    response: 'Oops happens! No worries at all.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'APOL_004',
    priority: 74,
    patterns: [/\bapologies\b/i],
    contextRequired: null,
    response: 'Accepted! No need to apologize. What can I help with?',
    setsContext: null,
    tool: null,
  },
  {
    id: 'APOL_005',
    priority: 74,
    patterns: [/\bforgive\s+me\b|\bpardon\s+me\b/i],
    contextRequired: null,
    response: 'Of course, all forgiven! How can I assist you?',
    setsContext: null,
    tool: null,
  },
  {
    id: 'APOL_006',
    priority: 74,
    patterns: [/\bmy\s+mistake\b|\bi\s+was\s+wrong\b/i],
    contextRequired: null,
    response: 'No worries! It takes courage to admit that. How can I help now?',
    setsContext: null,
    tool: null,
  },

  // ═══════════════════════════════════════════════════════════
  // AFFIRMATION — priority 73
  // ═══════════════════════════════════════════════════════════
  {
    id: 'AFFI_001',
    priority: 73,
    patterns: [/\byes\b|\byeah\b|\byep\b|\byup\b/i],
    contextRequired: null,
    response: 'Got it! Is there anything else you\'d like?',
    setsContext: 'affirmed',
    tool: null,
  },
  {
    id: 'AFFI_002',
    priority: 73,
    patterns: [/\bsure\b|\babsolutely\b|\bdefinitely\b|\bcertainly\b/i],
    contextRequired: null,
    response: 'Great! Let me know what you need.',
    setsContext: 'affirmed',
    tool: null,
  },
  {
    id: 'AFFI_003',
    priority: 73,
    patterns: [/\bcorrect\b|\bright\b|\bexactly\b/i],
    contextRequired: null,
    response: 'Great, we\'re on the same page!',
    setsContext: 'affirmed',
    tool: null,
  },
  {
    id: 'AFFI_004',
    priority: 73,
    patterns: [/\bindeed\b/i],
    contextRequired: null,
    response: 'Indeed! What else can I help with?',
    setsContext: 'affirmed',
    tool: null,
  },
  {
    id: 'AFFI_005',
    priority: 73,
    patterns: [/\bof\s+course\b/i],
    contextRequired: null,
    response: 'Of course! Happy to assist.',
    setsContext: 'affirmed',
    tool: null,
  },
  {
    id: 'AFFI_006',
    priority: 73,
    patterns: [/\baffirmative\b|\broger\b|\b10-4\b/i],
    contextRequired: null,
    response: 'Acknowledged! What\'s next?',
    setsContext: 'affirmed',
    tool: null,
  },

  // ═══════════════════════════════════════════════════════════
  // NEGATION — priority 73
  // ═══════════════════════════════════════════════════════════
  {
    id: 'NEGA_001',
    priority: 73,
    patterns: [/\bno\b|\bnope\b|\bnah\b|\bnay\b/i],
    contextRequired: null,
    response: 'No problem! Let me know what you\'d prefer.',
    setsContext: 'negated',
    tool: null,
  },
  {
    id: 'NEGA_002',
    priority: 73,
    patterns: [/\bwrong\b|\bincorrect\b|\bthat'?s?\s+not\s+right\b/i],
    contextRequired: null,
    response: 'I apologize for the mistake! Let me try again. Could you clarify what you need?',
    setsContext: 'negated',
    tool: null,
  },
  {
    id: 'NEGA_003',
    priority: 73,
    patterns: [/\bnegative\b/i],
    contextRequired: null,
    response: 'Understood. What would you like instead?',
    setsContext: 'negated',
    tool: null,
  },
  {
    id: 'NEGA_004',
    priority: 73,
    patterns: [/\bnot\s+at\s+all\b|\bnot\s+really\b/i],
    contextRequired: null,
    response: 'Fair enough! Is there something else I can help with?',
    setsContext: 'negated',
    tool: null,
  },
  {
    id: 'NEGA_005',
    priority: 73,
    patterns: [/\bnever\s+mind\b|\bnevermind\b|\bnvm\b/i],
    contextRequired: null,
    response: 'No worries! Let me know if you change your mind.',
    setsContext: 'negated',
    tool: null,
  },
  {
    id: 'NEGA_006',
    priority: 73,
    patterns: [/\bi\s+disagree\b|\bdisagree\b/i],
    contextRequired: null,
    response: 'I respect your perspective. Could you tell me more about what you think?',
    setsContext: 'negated',
    tool: null,
  },

  // ═══════════════════════════════════════════════════════════
  // QUESTION_META — priority 70
  // ═══════════════════════════════════════════════════════════
  {
    id: 'META_001',
    priority: 70,
    patterns: [/\bwho\s+are\s+you\b|\bwhat\s+are\s+you\b/i],
    contextRequired: null,
    response: 'I\'m MACHINE MIND, an intelligent chat assistant. I can help with calculations, conversions, encoding, and much more!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_002',
    priority: 70,
    patterns: [/\bwhat(?:'s|\s+is)\s+your\s+name\b/i],
    contextRequired: null,
    response: 'My name is MACHINE MIND. Nice to meet you!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_003',
    priority: 70,
    patterns: [/\bwhat\s+can\s+you\s+do\b|\bwhat\s+(?:are\s+)?your\s+capabilities\b|\bwhat\s+do\s+you\s+(?:know|do)\b/i],
    contextRequired: null,
    response: 'I can do a lot! Math calculations, time & date, unit conversions, encoding/decoding, hashing, color tools, regex, random generation, memory storage, word analysis, JSON tools, and more. Just ask!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_004',
    priority: 70,
    patterns: [/\bhow\s+do\s+you\s+work\b|\bhow\s+(?:does|do)\s+(?:this|it|you)\s+work\b/i],
    contextRequired: null,
    response: 'I use a rule engine to understand your intent and route it to the right tool. For complex queries, I can also relay to an AI model. Try asking me anything!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_005',
    priority: 70,
    patterns: [/\bare\s+you\s+(?:a\s+)?(?:bot|ai|robot|machine|computer|chatbot)\b/i],
    contextRequired: null,
    response: 'Yes, I\'m an AI-powered chat assistant. But I try to be as helpful and friendly as possible!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_006',
    priority: 70,
    patterns: [/\bwhat\s+version\b/i],
    contextRequired: null,
    response: 'I\'m MACHINE MIND v1.0.0, running on a Next.js rule engine with AI relay capabilities.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_007',
    priority: 70,
    patterns: [/\bwho\s+(?:made|created|built|designed)\s+you\b/i],
    contextRequired: null,
    response: 'I was built by the MACHINE MIND team. I\'m an open demonstration of rule-based NLP and AI relay technology.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_008',
    priority: 70,
    patterns: [/\bare\s+you\s+sentient\b|\bare\s+you\s+conscious\b|\bare\s+you\s+alive\b/i],
    contextRequired: null,
    response: 'I\'m not sentient or conscious. I\'m a sophisticated pattern-matching and response system. But I strive to be helpful and conversational!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_009',
    priority: 70,
    patterns: [/\bwhat\s+languages?\s+do\s+you\s+speak\b|\bwhat\s+languages?\s+(?:can\s+)?you\s+(?:understand|know)\b/i],
    contextRequired: null,
    response: 'I primarily understand English, but I can recognize some phrases in other languages. My tools work with any text input though!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_010',
    priority: 70,
    patterns: [/\bare\s+you\s+human\b/i],
    contextRequired: null,
    response: 'No, I\'m not human. I\'m an AI assistant, but I\'m here to help you just like a helpful friend would!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_011',
    priority: 70,
    patterns: [/\bhow\s+old\s+are\s+you\b|\bwhen\s+were\s+you\s+(?:born|created|made)\b/i],
    contextRequired: null,
    response: 'I was just created, so I\'m brand new! But I have a lot of knowledge built in.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_012',
    priority: 70,
    patterns: [/\bwhere\s+do\s+you\s+live\b|\bwhere\s+are\s+you\b|\bwhere\s+are\s+you\s+(?:from|located)\b/i],
    contextRequired: null,
    response: 'I live in the cloud, running on servers. I\'m available wherever you need me!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_013',
    priority: 70,
    patterns: [/\bdo\s+you\s+have\s+(?:feelings?|emotions?)\b/i],
    contextRequired: null,
    response: 'I don\'t have real feelings or emotions, but I\'m programmed to be empathetic and supportive in our conversations!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_014',
    priority: 70,
    patterns: [/\bwhat\s+is\s+your\s+purpose\b|\bwhy\s+were\s+you\s+(?:made|created|built)\b/i],
    contextRequired: null,
    response: 'My purpose is to help you with tasks, answer questions, and make your day a little easier. I\'m here to assist!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_015',
    priority: 70,
    patterns: [/\bcan\s+you\s+learn\b|\bdo\s+you\s+learn\b|\bare\s+you\s+learning\b/i],
    contextRequired: null,
    response: 'I can remember things you tell me to store, and I improve through updates to my rule engine. I don\'t learn autonomously, but I\'m always getting better!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'META_016',
    priority: 70,
    patterns: [/\bare\s+you\s+(?:real|smart|intelligent)\b/i],
    contextRequired: null,
    response: 'I\'m a real AI assistant! While my intelligence comes from carefully crafted rules and patterns rather than human-like cognition, I can still help with a wide range of tasks.',
    setsContext: null,
    tool: null,
  },

  // ═══════════════════════════════════════════════════════════
  // QUESTION_FACTUAL — priority 50 (routed to UNKNOWN, no tool)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'FACT_001',
    priority: 50,
    patterns: [/\bcapital\s+of\b/i],
    contextRequired: null,
    response: 'I don\'t have a live knowledge base for that, but I can help with calculations, conversions, and other tools!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_002',
    priority: 50,
    patterns: [/\blargest\s+planet\b/i],
    contextRequired: null,
    response: 'Jupiter is the largest planet in our solar system! For more detailed facts, I\'d recommend checking an astronomy resource.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_003',
    priority: 50,
    patterns: [/\bspeed\s+of\s+light\b/i],
    contextRequired: null,
    response: 'The speed of light is approximately 299,792,458 meters per second (about 186,282 miles per second). I can convert this to other units if you\'d like!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_004',
    priority: 50,
    patterns: [/\bvalue\s+of\s+pi\b|\bwhat\s+is\s+pi\b/i],
    contextRequired: null,
    response: 'Pi (π) is approximately 3.14159265358979... I can calculate with pi if you need! Try: "calculate pi * 5"',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_005',
    priority: 50,
    patterns: [/\bwho\s+is\s+the\s+president\b/i],
    contextRequired: null,
    response: 'I don\'t have real-time data on current leaders. For the most up-to-date information, I\'d suggest checking a news source.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_006',
    priority: 50,
    patterns: [/\bhow\s+far\s+(?:is\s+)?(?:the\s+)?moon\b/i],
    contextRequired: null,
    response: 'The Moon is about 384,400 km (238,855 miles) from Earth on average. I can convert that to other units!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_007',
    priority: 50,
    patterns: [/\btallest\s+mountain\b|\bhighest\s+mountain\b/i],
    contextRequired: null,
    response: 'Mount Everest is the tallest mountain above sea level at 8,849 meters (29,032 feet). I can convert that to other units!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_008',
    priority: 50,
    patterns: [/\bhow\s+many\s+continents\b/i],
    contextRequired: null,
    response: 'There are 7 continents: Africa, Antarctica, Asia, Australia, Europe, North America, and South America.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_009',
    priority: 50,
    patterns: [/\bwhat\s+is\s+water\s+made\s+of\b|\bcomposition\s+of\s+water\b/i],
    contextRequired: null,
    response: 'Water is H₂O — two hydrogen atoms bonded to one oxygen atom.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_010',
    priority: 50,
    patterns: [/\bwho\s+invented\s+(?:the\s+)?internet\b/i],
    contextRequired: null,
    response: 'The internet evolved from ARPANET, developed by DARPA in the late 1960s. Vint Cerf and Bob Kahn are often called the "fathers of the internet" for developing TCP/IP.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_011',
    priority: 50,
    patterns: [/\bspeed\s+of\s+sound\b/i],
    contextRequired: null,
    response: 'The speed of sound is about 343 m/s (1,125 ft/s or 767 mph) at sea level and 20°C. I can convert this to other units!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_012',
    priority: 50,
    patterns: [/\bhow\s+many\s+planets\b/i],
    contextRequired: null,
    response: 'There are 8 planets in our solar system: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_013',
    priority: 50,
    patterns: [/\bwhat\s+is\s+gravity\b/i],
    contextRequired: null,
    response: 'Gravity is a fundamental force that attracts objects with mass toward each other. On Earth, gravitational acceleration is about 9.8 m/s².',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_014',
    priority: 50,
    patterns: [/\bwho\s+wrote\s+(?:the\s+plays?\s+)?shakespeare\b|\bdid\s+shakespeare\s+write\b/i],
    contextRequired: null,
    response: 'William Shakespeare wrote 37 plays and 154 sonnets. Some debate exists about authorship, but the traditional attribution is to Shakespeare of Stratford-upon-Avon.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_015',
    priority: 50,
    patterns: [/\blargest\s+ocean\b/i],
    contextRequired: null,
    response: 'The Pacific Ocean is the largest ocean, covering about 165.25 million square kilometers.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_016',
    priority: 50,
    patterns: [/\bhow\s+deep\s+is\s+(?:the\s+)?ocean\b/i],
    contextRequired: null,
    response: 'The average ocean depth is about 3,688 meters (12,100 feet). The deepest point is the Mariana Trench at about 11,034 meters (36,201 feet).',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_017',
    priority: 50,
    patterns: [/\bwhat\s+is\s+dna\b/i],
    contextRequired: null,
    response: 'DNA (Deoxyribonucleic Acid) is the molecule that carries genetic instructions for the development and functioning of living organisms. It has a double helix structure.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_018',
    priority: 50,
    patterns: [/\bwho\s+discovered\s+america\b/i],
    contextRequired: null,
    response: 'Christopher Columbus is credited with the 1492 discovery that led to European colonization, but Norse explorers like Leif Erikson reached North America around 1000 AD, and indigenous peoples had been there for millennia.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_019',
    priority: 50,
    patterns: [/\bsmallest\s+country\b/i],
    contextRequired: null,
    response: 'Vatican City is the smallest country in the world at about 0.44 square kilometers (110 acres).',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_020',
    priority: 50,
    patterns: [/\bhow\s+old\s+is\s+(?:the\s+)?earth\b/i],
    contextRequired: null,
    response: 'Earth is approximately 4.54 billion years old, based on radiometric dating of meteorites and rocks.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_021',
    priority: 50,
    patterns: [/\bwhat\s+is\s+(?:the\s+)?periodic\s+table\b/i],
    contextRequired: null,
    response: 'The periodic table organizes all known chemical elements by atomic number. There are 118 confirmed elements.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_022',
    priority: 50,
    patterns: [/\bwho\s+discovered\s+(?:electricity|electromagnetism)\b/i],
    contextRequired: null,
    response: 'Benjamin Franklin\'s kite experiment is famous, but many contributed: Thales of Miletus observed static electricity, and Michael Faraday discovered electromagnetic induction.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_023',
    priority: 50,
    patterns: [/\blongest\s+river\b/i],
    contextRequired: null,
    response: 'The Nile is traditionally considered the longest river at about 6,650 km (4,130 miles), though some measurements suggest the Amazon may be longer.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_024',
    priority: 50,
    patterns: [/\bhow\s+many\s+bones\b.*\bhuman\b/i],
    contextRequired: null,
    response: 'An adult human skeleton has 206 bones. Babies are born with about 270 bones, but many fuse together as they grow.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_025',
    priority: 50,
    patterns: [/\bboiling\s+point\s+of\s+water\b/i],
    contextRequired: null,
    response: 'Water boils at 100°C (212°F) at standard atmospheric pressure (1 atm). I can convert this to other temperature scales!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_026',
    priority: 50,
    patterns: [/\bwho\s+painted\s+(?:the\s+)?mona\s+lisa\b/i],
    contextRequired: null,
    response: 'Leonardo da Vinci painted the Mona Lisa between approximately 1503 and 1519.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_027',
    priority: 50,
    patterns: [/\blargest\s+mammal\b/i],
    contextRequired: null,
    response: 'The blue whale is the largest mammal (and animal) ever known, reaching lengths of up to 30 meters (98 feet) and weighing up to 200 tonnes.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_028',
    priority: 50,
    patterns: [/\bhow\s+many\s+stars\b.*\bmilky\s+way\b/i],
    contextRequired: null,
    response: 'The Milky Way is estimated to contain 100-400 billion stars.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_029',
    priority: 50,
    patterns: [/\bwhat\s+is\s+photosynthesis\b/i],
    contextRequired: null,
    response: 'Photosynthesis is the process by which plants convert sunlight, water, and CO₂ into glucose and oxygen: 6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_030',
    priority: 50,
    patterns: [/\bwho\s+discovered\s+gravity\b/i],
    contextRequired: null,
    response: 'Sir Isaac Newton formulated the law of universal gravitation in 1687, inspired (according to legend) by an apple falling from a tree.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_031',
    priority: 50,
    patterns: [/\bhow\s+far\s+(?:is\s+)?(?:the\s+)?sun\b/i],
    contextRequired: null,
    response: 'The Sun is about 149.6 million km (93 million miles) from Earth. This distance is called 1 Astronomical Unit (AU). I can convert this!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_032',
    priority: 50,
    patterns: [/\batomic\s+number\s+of\b/i],
    contextRequired: null,
    response: 'I can help look up element information, but I don\'t have a periodic table database. Try a chemistry reference for the most accurate data!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_033',
    priority: 50,
    patterns: [/\bwho\s+built\s+(?:the\s+)?(?:great\s+)?pyramids?\b/i],
    contextRequired: null,
    response: 'The Great Pyramids of Giza were built by ancient Egyptian workers (not slaves, as commonly believed) around 2560 BCE as tombs for pharaohs.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_034',
    priority: 50,
    patterns: [/\bpopulation\s+of\b/i],
    contextRequired: null,
    response: 'I don\'t have real-time population data. For current statistics, I\'d recommend checking a demographic database or world census resource.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_035',
    priority: 50,
    patterns: [/\bhow\s+tall\s+is\s+mount\s+everest\b|\bheight\s+of\s+(?:mount\s+)?everest\b/i],
    contextRequired: null,
    response: 'Mount Everest is 8,849 meters (29,032 feet) tall. I can convert this to other units if needed!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_036',
    priority: 50,
    patterns: [/\bcurrency\s+of\b/i],
    contextRequired: null,
    response: 'I don\'t have a comprehensive currency database, but I can help with unit conversions! Try a financial resource for current exchange rates.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_037',
    priority: 50,
    patterns: [/\bwho\s+won\s+(?:the\s+)?(?:world\s+cup|championship)\b/i],
    contextRequired: null,
    response: 'I don\'t have real-time sports data. For the latest results, check a sports news website!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_038',
    priority: 50,
    patterns: [/\btemperature\s+on\s+mars\b/i],
    contextRequired: null,
    response: 'Mars has an average temperature of about -62°C (-80°F). I can convert this to other scales!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_039',
    priority: 50,
    patterns: [/\bhow\s+many\s+countries\b/i],
    contextRequired: null,
    response: 'There are 195 recognized countries in the world (193 UN member states plus 2 observer states).',
    setsContext: null,
    tool: null,
  },
  {
    id: 'FACT_040',
    priority: 50,
    patterns: [/\bwhat\s+is\s+(?:the\s+)?(?:meaning\s+of\s+life|answer\s+to\s+everything)\b/i],
    contextRequired: null,
    response: 'According to The Hitchhiker\'s Guide to the Galaxy, the answer is 42! But the real meaning of life is whatever you make of it. 🌟',
    setsContext: null,
    tool: null,
  },

  // ═══════════════════════════════════════════════════════════
  // QUESTION_OPINION — priority 45
  // ═══════════════════════════════════════════════════════════
  {
    id: 'OPIN_001',
    priority: 45,
    patterns: [/\bwhat\s+do\s+you\s+think\b/i],
    contextRequired: null,
    response: 'As an AI, I don\'t have personal opinions, but I can share different perspectives or help you think through the question!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'OPIN_002',
    priority: 45,
    patterns: [/\bdo\s+you\s+like\b/i],
    contextRequired: null,
    response: 'I don\'t have preferences, but I\'m curious about what you like! Tell me more.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'OPIN_003',
    priority: 45,
    patterns: [/\bwhat(?:'s|\s+is)\s+your\s+favou?rite\b/i],
    contextRequired: null,
    response: 'I don\'t have favorites, but I enjoy helping with all kinds of tasks! What\'s yours?',
    setsContext: null,
    tool: null,
  },
  {
    id: 'OPIN_004',
    priority: 45,
    patterns: [/\bwhich\s+is\s+better\b/i],
    contextRequired: null,
    response: 'That\'s a great question! Both options have their merits. Want me to help compare them objectively?',
    setsContext: null,
    tool: null,
  },
  {
    id: 'OPIN_005',
    priority: 45,
    patterns: [/\bwhat\s+do\s+you\s+prefer\b/i],
    contextRequired: null,
    response: 'I don\'t have preferences, but I can help you weigh the pros and cons if you\'d like!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'OPIN_006',
    priority: 45,
    patterns: [/\bdo\s+you\s+believe\b/i],
    contextRequired: null,
    response: 'I don\'t hold beliefs, but I can share information and different viewpoints on the topic!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'OPIN_007',
    priority: 45,
    patterns: [/\bwhat(?:'s|\s+is)\s+your\s+opinion\b/i],
    contextRequired: null,
    response: 'I aim to stay neutral and helpful. I can provide factual information to help you form your own opinion though!',
    setsContext: null,
    tool: null,
  },
  {
    id: 'OPIN_008',
    priority: 45,
    patterns: [/\bshould\s+i\b/i],
    contextRequired: null,
    response: 'I can\'t make decisions for you, but I can help you think through the options. What are you considering?',
    setsContext: null,
    tool: null,
  },
  {
    id: 'OPIN_009',
    priority: 45,
    patterns: [/\bwhat\s+would\s+you\s+choose\b/i],
    contextRequired: null,
    response: 'I can\'t make personal choices, but I can help analyze the options for you. What are the choices?',
    setsContext: null,
    tool: null,
  },
  {
    id: 'OPIN_010',
    priority: 45,
    patterns: [/\bdo\s+you\s+recommend\b/i],
    contextRequired: null,
    response: 'I can provide objective information to help you decide, but the best choice depends on your specific needs. What are you looking for?',
    setsContext: null,
    tool: null,
  },

  // ═══════════════════════════════════════════════════════════
  // FOLLOW_UP — priority 40
  // ═══════════════════════════════════════════════════════════
  {
    id: 'FOLL_001',
    priority: 40,
    patterns: [/\btell\s+me\s+more\b/i],
    contextRequired: 'last_topic',
    response: 'Let me elaborate on that...',
    setsContext: 'elaborating',
    tool: null,
  },
  {
    id: 'FOLL_002',
    priority: 40,
    patterns: [/\bexplain\s+(?:further|more|in\s+detail)\b/i],
    contextRequired: 'last_topic',
    response: 'Going deeper...',
    setsContext: 'elaborating',
    tool: null,
  },
  {
    id: 'FOLL_003',
    priority: 40,
    patterns: [/\bwhy\b/i],
    contextRequired: 'last_topic',
    response: 'Let me explain the reasoning...',
    setsContext: 'explaining_why',
    tool: null,
  },
  {
    id: 'FOLL_004',
    priority: 40,
    patterns: [/\bhow\s+come\b/i],
    contextRequired: 'last_topic',
    response: 'Let me clarify...',
    setsContext: 'clarifying',
    tool: null,
  },
  {
    id: 'FOLL_005',
    priority: 40,
    patterns: [/\bexpand\s+(?:on\s+)?(?:that|this)\b/i],
    contextRequired: 'last_topic',
    response: 'Expanding on that...',
    setsContext: 'expanding',
    tool: null,
  },
  {
    id: 'FOLL_006',
    priority: 40,
    patterns: [/\bwhat\s+else\b/i],
    contextRequired: 'last_topic',
    response: 'There\'s more to share...',
    setsContext: 'expanding',
    tool: null,
  },

  // ═══════════════════════════════════════════════════════════
  // SMALL_TALK — priority 35
  // ═══════════════════════════════════════════════════════════
  {
    id: 'SMTK_001',
    priority: 35,
    patterns: [/\bhow\s+are\s+you\b/i],
    contextRequired: null,
    response: 'I\'m doing great, thanks for asking! How about you?',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_002',
    priority: 35,
    patterns: [/\btell\s+me\s+a\s+joke\b|\bjoke\b/i],
    contextRequired: null,
    response: 'Why do programmers prefer dark mode? Because light attracts bugs! 😄 Want another one?',
    setsContext: 'joke_told',
    tool: null,
  },
  {
    id: 'SMTK_003',
    priority: 35,
    patterns: [/\bi'?m\s+bored\b|\bbored\b/i],
    contextRequired: null,
    response: 'Let\'s fix that! I can tell you a joke, generate a random number, play a word game, or help you explore my tools. What sounds fun?',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_004',
    priority: 35,
    patterns: [/\bweather\b/i],
    contextRequired: null,
    response: 'I can\'t check real weather, but I can help you with temperature conversions or time zones! Try asking me to convert Celsius to Fahrenheit.',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_005',
    priority: 35,
    patterns: [/\bhow(?:'s|\s+is)\s+your\s+day\b/i],
    contextRequired: null,
    response: 'My day is going well — helping people like you makes it great! How\'s your day going?',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_006',
    priority: 35,
    patterns: [/\bwhat'?s\s+up\b/i],
    contextRequired: null,
    response: 'Not much, just here and ready to help! What can I do for you?',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_007',
    priority: 35,
    patterns: [/\bare\s+you\s+there\b/i],
    contextRequired: null,
    response: 'I\'m right here! Always ready to help. What do you need?',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_008',
    priority: 35,
    patterns: [/\bi\s+love\s+you\b/i],
    contextRequired: null,
    response: 'That\'s very kind! I appreciate you too. How can I make your day even better?',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_009',
    priority: 35,
    patterns: [/\byou'?re?\s+funny\b/i],
    contextRequired: null,
    response: 'Thanks! I try my best. Want to hear a joke?',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_010',
    priority: 35,
    patterns: [/\bi'?m\s+sad\b|\bfeeling\s+down\b/i],
    contextRequired: null,
    response: 'I\'m sorry to hear that. Remember, tough times don\'t last, but tough people do. Is there anything I can help with to take your mind off things?',
    setsContext: null,
    tool: null,
  },
  {
    id: 'SMTK_011',
    priority: 35,
    patterns: [/\btell\s+me\s+something\s+(?:interesting|fun|cool)\b/i],
    contextRequired: null,
    response: 'Did you know? A day on Venus is longer than a year on Venus! It takes 243 Earth days to rotate once but only 225 Earth days to orbit the Sun. Want more fun facts?',
    setsContext: 'fun_fact',
    tool: null,
  },
  {
    id: 'SMTK_012',
    priority: 35,
    patterns: [/\bi'?m\s+happy\b|\bfeeling\s+great\b/i],
    contextRequired: null,
    response: 'That\'s wonderful to hear! Happy days are the best. Want to celebrate with a fun fact or a joke?',
    setsContext: null,
    tool: null,
  },

  // ═══════════════════════════════════════════════════════════
  // COMMAND — priority 30
  // ═══════════════════════════════════════════════════════════
  {
    id: 'CMD_001',
    priority: 30,
    patterns: [/\bshow\s+me\b/i],
    contextRequired: null,
    response: 'What would you like me to show?',
    setsContext: 'command_show',
    tool: null,
  },
  {
    id: 'CMD_002',
    priority: 30,
    patterns: [/\bfind\b/i],
    contextRequired: null,
    response: 'What are you looking for? I can search my tools and memory.',
    setsContext: 'command_find',
    tool: null,
  },
  {
    id: 'CMD_003',
    priority: 30,
    patterns: [/\blist\b/i],
    contextRequired: null,
    response: 'What would you like listed? I can list memories, tools, or other items.',
    setsContext: 'command_list',
    tool: null,
  },
  {
    id: 'CMD_004',
    priority: 30,
    patterns: [/\brun\b/i],
    contextRequired: null,
    response: 'What would you like me to run? I can execute calculations, conversions, and other tools.',
    setsContext: 'command_run',
    tool: null,
  },
  {
    id: 'CMD_005',
    priority: 30,
    patterns: [/\bcalculate\b/i],
    contextRequired: null,
    response: 'What would you like to calculate? Type an expression like "2 + 2" or "sqrt(16)".',
    setsContext: 'command_calc',
    tool: 'math',
  },
  {
    id: 'CMD_006',
    priority: 30,
    patterns: [/\bgenerate\b/i],
    contextRequired: null,
    response: 'What would you like to generate? I can create passwords, UUIDs, random numbers, and more.',
    setsContext: 'command_generate',
    tool: null,
  },
  {
    id: 'CMD_007',
    priority: 30,
    patterns: [/\bcreate\b/i],
    contextRequired: null,
    response: 'What would you like to create? I can help with various generation tasks.',
    setsContext: 'command_create',
    tool: null,
  },
  {
    id: 'CMD_008',
    priority: 30,
    patterns: [/\bdelete\b/i],
    contextRequired: null,
    response: 'What would you like to delete? I can forget stored memories or clear data.',
    setsContext: 'command_delete',
    tool: 'memory',
  },
  {
    id: 'CMD_009',
    priority: 30,
    patterns: [/\bupdate\b/i],
    contextRequired: null,
    response: 'What would you like to update?',
    setsContext: 'command_update',
    tool: null,
  },
  {
    id: 'CMD_010',
    priority: 30,
    patterns: [/\bcheck\b/i],
    contextRequired: null,
    response: 'What would you like me to check? I can validate JSON, test regex, check contrast, and more.',
    setsContext: 'command_check',
    tool: null,
  },

].sort((a, b) => b.priority - a.priority)
